### ISSUE TITLE
Difference between `localization_branch_name` and `crowdin_branch_name`

### ISSUE THREAD

**Issue by zeke** [crowdin/github-action#10]
In the README I see `localization_branch_name` and `crowdin_branch_name` options, but don't know exactly what they mean. Here are my assumptions:

- `localization_branch_name` is the name of the git branch that Crowdin will create when opening a pull request.
- `crowdin_branch_name` is the name of the top-level directory that Crowdin will use for files.
- Neither of these branches need to be manually created. They will be created automatically by the Action.

Are those assumptions correct? Once I know for sure I can open a PR to clarify the documentation.

**Comment by VBeytok** [comment]
@zeke yes, all your assumptions are correct.

**Comment by zeke** [comment]
I opened a PR for this: https://github.com/crowdin/github-action/pull/12
