### ISSUE TITLE
Path structure is not kept while uploading sources

### ISSUE THREAD

**Issue by andi34** [crowdin/github-action#105]
**Describe the bug**
Path to the file to translate is defined, but the folder structure is if ignored.

Defined:
folder1/folder2/file

Uploads to:
folder1/file

**To Reproduce**
1. Crowdin Github Action configuration
2. `crowdin.yml` file content
3. Information about workflow (OS, steps, etc.)

My workflow: https://github.com/andi34/photobooth/blob/dev/.github/workflows/crowdin.yml

**Expected behavior**
Uploaded source should keep the folder structure.

Issue on my setup?

**Screenshots**

**Additional context**

**Comment by ira-sem** [comment]
Hi @andi34 ! thanks for reporting, passing to our tech team.

**Comment by andrii-bodnar** [comment]
Hi @andi34!

To save directory structure on a server you need to use the `preserve_hierarchy` option - [Saving Directory Structure on Server](https://support.crowdin.com/configuration-file/#saving-directory-structure-on-server).

This option is not available through GH action parameters, so you can create the `crowdin.yml` configuration file and set the `preserve_hierarchy` as `true`.

Also, you can move your source and translations patterns to the configuration file.

Your `crowdin.yml` might look like:

```json
"preserve_hierarchy": true

"files": [
  {
    "source": "resources/lang/en.json",
    "translation": "resources/lang/%two_letters_code%.json"
  }
]
```

After that, you ned to reupload your source files to Crowdin via Crowdin GH Action.

**Comment by andi34** [comment]
Thanks a lot! Worked fine 😃

**Comment by andi34** [comment]
Do you mind telling me, which permissions I need to set on the GitHub token to upload downloaded translations automatically?

**Comment by andrii-bodnar** [comment]
@andi34 you need the `repo` scopes.

**Comment by andi34** [comment]
Great, thanks a lot!
I've to name it time something else than "GITHUB_TOKEN", e.g. "REPO_TOKEN", that's right?
I am also unsure, I need to add it as Repository secrets or Environment secrets?

Sorry if those questions sounding stupid 🙈

**Comment by andrii-bodnar** [comment]
@andi34 you can name this token whatever you want, just pass the correct token name to the GH Action config:

```
GITHUB_TOKEN: ${{ secrets.MY_SUPER_TOKEN }}
```

> I am also unsure, I need to add it as Repository secrets or Environment secrets?

Click repo 'Settings', then 'Secrets' > 'Actions' > 'New repository secret' and then create a secret using your token.
