### ISSUE TITLE
Does the action support downloading and committing translations directly to the default branch?

### ISSUE THREAD

**Issue by zeshuaro** [crowdin/github-action#110]
It's not clear in the README that whether this is supported, would someone be able to clarify if the action can download and commit translations directly to the default branch instead of creating a pull request? I also don't want to test this out in my repo which might mess up the commit history.

I can see that there are the options `create_pull_request` and `localization_branch_name`. If I set `create_pull_request` to `false` and set `localization_branch_name` to the default branch, will the action achieve what I described above?

**Comment by conconnl** [comment]
It does a direct commit in the localization branch which is not the same as the source branch.
After it's finished it can create a pull request and a direct commit into your main branch.
Of course you could look at things like auto-merge GitHub action: https://github.com/marketplace/actions/auto-merge-pull-request

**Comment by zeshuaro** [comment]
If that's the case can I turn this into a feature request to support direct commit to the source/default branch?

Although using an auto-merge action seems to be a good workaround, this will require 2 separate action runs in order to get the updated translations committed and/or deployed. I would like to be able to commit and deploy the updated translations in a single action run if that makes sense.

**Comment by brokelyn** [comment]
@zeshuaro I was searching for the same feature as you and just tried your suggestion setting `create_pull_request` to `false` and setting `localization_branch_name` to `master` (in my case). These settings worked for my and I got a commit straight into master. But it seems like this commit cannot trigger any further Github actions.

**Comment by zeshuaro** [comment]
@brokelyn you are a legend! I was too lazy to test it out myself. But I tested this out just then and also managed to commit onto `master` directly with the action.

I'm not sure what your workflow/action is, but it is not required for me to trigger another action with the new commit. My workflow would simply build a Docker image right after the new translations are downloaded and run the deployment.

Below is my workflow, hope it helps, and I'm closing this issue 🙂 

**Config:** https://github.com/zeshuaro/telegram-pdf-bot/blob/master/.github/workflows/github-actions.yml#L90-L190
**Example run:** https://github.com/zeshuaro/telegram-pdf-bot/runs/7764882662?check_suite_focus=true
