### ISSUE TITLE
Crowdin action creates no pull request

### ISSUE THREAD

**Issue by NotMyFault** [crowdin/github-action#112]
Heyo, 

I'm looking forward to use the GitHub action to pull translations from Crowdin.
I added the action to the following repository, but it doesn't create a pull request: https://github.com/NotMyFault/design-library-plugin
I configured the action to export approved strings only and create a pull request based on it, however, no pull request is created.
I approved a string on my crowdin enterprise instance beforehand.

The workflow file is available here: https://github.com/NotMyFault/design-library-plugin/blob/master/.github/workflows/crowdin.yml
The project is named "dlib" on https://intellectualsites.crowdin.com/
The unsuccessful workflow is here: https://github.com/NotMyFault/design-library-plugin/actions/runs/2061347585

I hope someone could help me out.
Thanks in advance!

**Comment by andrii-bodnar** [comment]
Hi @NotMyFault!

Probably you have enabled the **Skip untranslated files** option in your Crowdin Enterprise project and there are no fully translated files in any language. The warning `⚠️  Couldn't find any file to download` means that there are no files in the extracted archive downloaded from Crowdin.

Please make sure you have fully translated files or just disable this option.

**Comment by NotMyFault** [comment]
Thanks for your quick response, that actually was it. I wasn't sure whether I need to enable it but it seems that the action already takes care of it.
Unfortunately, it doesn't create a PR still, it fails with the error
` ! [remote rejected] l10n_crowdin_action -> l10n_crowdin_action (refusing to allow a GitHub App to create or update workflow `.github/workflows/crowdin.yml` without `workflows` permission)
`
https://github.com/NotMyFault/design-library-plugin/runs/5749938987?check_suite_focus=true#step:4:51
Is there anything else I need to configure?

**Comment by andrii-bodnar** [comment]
@NotMyFault please try to select `workflow` permission for the GH Token used for this Action

**Comment by NotMyFault** [comment]
> @NotMyFault please try to select `workflow` permission for the GH Token used for this Action

The workflow token already has read and write permission
![](https://i.imgur.com/RWHJYZi.png)

I've now granted explicit permission via 
```yml
permissions:
  actions: write
```
though it used to work before without.

Anyway, it now fails with 
```
remote: Permission to NotMyFault/design-library-plugin.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/NotMyFault/design-library-plugin.git/': The requested URL returned error: 403
```
https://github.com/NotMyFault/design-library-plugin/runs/5750401457?check_suite_focus=true#step:4:51

Any recommendations?

**Comment by andrii-bodnar** [comment]
@VBeytok could you please assist with the permissions?

**Comment by NotMyFault** [comment]
I got it working by setting explicit permission on the workflow:
```yaml
permissions:
  actions: write
  contents: write
  pull-requests: write
```
Yet that looks to be a logic flaw somewhere, because the default permission is write on everything if not changed in the Actions tab.

**Comment by NotMyFault** [comment]
I got everything working so far with this hacky solution, I've set `skip_untranslated_strings: true` and `skip_untranslated_files: true`
and the workflow complains about
```
❌ Some of the command options are invalid. Check the following parameters:
	- Sorry, you cannot skip strings and files simultaneously. Please use one of these parameters instead.
```
If I enable only `skip_untranslated_strings` I end up with untranslated files and if I set only `skip_untranslated_files` I don't get partly translated files with only a few strings if not everything is translated yet.
Is there no middleway to only get translated strings _and_ skip untranslated files?

**Comment by andrii-bodnar** [comment]
@NotMyFault using only `skip_untranslated_files` will allow you to download only those files, that are fully translated. As a result - you will receive only translated files without untranslated ones.

**Comment by NotMyFault** [comment]
> @NotMyFault using only `skip_untranslated_files` will allow you to download only those files, that are fully translated. As a result - you will receive only translated files without untranslated ones.

I figured, but I was wondering if there is no intermediary way to ship only parts of translated strings, like you can do through the web interface.
`skip_untranslated_strings` creates this PR: https://github.com/NotMyFault/design-library-plugin/pull/3/files
This is _almost_ what I want; partly translated files are shipped while untranslated strings are ignored, however, it creates empty files which are not yet translated which I want to skip.

**Comment by andrii-bodnar** [comment]
@NotMyFault probably the only way is to use `skip_untranslated_files`

**Comment by NotMyFault** [comment]
That'll work for my use case, I guess. Thanks for your help so far.
