### ISSUE TITLE
Setting the translation parameter should not change the project configuration

### ISSUE THREAD

**Issue by richardsd** [crowdin/github-action#134]
Hey team, I don't really know if this exactly an issue, but it doesn't feel right to me.
I have a crowdin project with the folowing structure, with different source files on different directories:

```
root
- folder1
-- messages.json
- folder2
-- messages.json
- messages.json
```

The top level `messages.json` has the following export configuration:
![Screenshot 2022-07-04 at 09 37 53](https://user-images.githubusercontent.com/738700/177116583-95b83728-bb7d-4328-92d6-9adc2e24901e.png)

On GH I have a workflow that uses the `crowdin/github-action@1.4.9` and I set the `translation` parameter with: `/i18n/messages-%two_letters_code%.json`. I'm doing this mapping because in my local project, the translations are located in a different directory.

The problem is that when I pass the parameter with this value, the project configuration is updated and if I go the Crowdin project to download it, it is using the last configuration provided by the github action, and not the one I manually add to the project.
![Screenshot 2022-07-04 at 09 41 27](https://user-images.githubusercontent.com/738700/177117130-99d97226-d2a9-457d-8d55-5b5a8025c0ce.png)

I don't think that overriding the configuration should be the expected behavior, but is this a bug, or an intended feature? Thank you team, waiting for your feedback.

**Comment by dianaIosm** [comment]
Hello @richardsd! 

This is the expected behavior since the file would be exported according to the configuration option you've saved.  Otherwise, the Github Action for this file would not be functional. 

The same file can't have two different export options within one project. 

Hope this answers your question!

**Comment by andrii-bodnar** [comment]
Hi @Gabez0r,

The Crowdin GH Action is based on the Crowdin CLI. CLI is closely connected to the translation pattern. 

The possible solution is to use branches in Crowdin - files within each branch will have their own structure and translation pattern. The duplicated strings could be managed using the [duplicates strategies](https://support.crowdin.com/versions-management/#duplicates).

**Comment by Gabez0r** [comment]
Thank you for the response, @andrii-bodnar. So, if we want to have the very same translations and just use two different translation formats, i.e, export the files with a different pattern, but without having the config constantly switching between exports, we should have two branches duplicating the same content?

**Comment by andrii-bodnar** [comment]
@Gabez0r could you please a more detailed example of your setup? Maybe there is another solution but I need to better understand your use case

**Comment by andrii-bodnar** [comment]
Hi @richardsd, @Gabez0r,

There is a new alternative GH Actions solution that is not based on the Crowdin CLI and can be used without affecting the "Translations export pattern" - [Crowdin Request Action](https://github.com/andrii-bodnar/crowdin-request-action)

Maybe, it could help with your use cases as it gives more flexibility since you have more control and freedom on the Crowdin API usage

**Comment by richardsd** [comment]
Hey @andrii-bodnar,

Thanks for getting back to us on this subject. We are not actively working on the topic anymore, as we based our solution on current behavior for now (and we are now in a new team), but I'll make sure that this information is passed on to the new team. 
Thank you very much.
