### ISSUE TITLE
gateway timeout while running the action errors

### ISSUE THREAD

**Issue by laurentleseigneur** [crowdin/github-action#140]
**Describe the bug**
I get some gateway timeout while running the action. is it related to end point or action configuration ? 

**To Reproduce**
Run crowdin/github-action@1.4.12
  
/usr/bin/docker run --name a9bdc594fca37a745e0a94a236b50f9d1cd_e76245 --label 786a9b --workdir /github/workspace --rm -e "GITHUB_TOKEN" -e "CROWDIN_PROJECT_ID" -e "CROWDIN_PERSONAL_TOKEN" -e "INPUT_UPLOAD_SOURCES" -e "INPUT_UPLOAD_TRANSLATIONS" -e "INPUT_DOWNLOAD_TRANSLATIONS" -e "INPUT_LOCALIZATION_BRANCH_NAME" -e "INPUT_CREATE_PULL_REQUEST" -e "INPUT_PROJECT_ID" -e "INPUT_TOKEN" -e "INPUT_UPLOAD_SOURCES_ARGS" -e "INPUT_UPLOAD_LANGUAGE" -e "INPUT_AUTO_APPROVE_IMPORTED" -e "INPUT_IMPORT_EQ_SUGGESTIONS" -e "INPUT_UPLOAD_TRANSLATIONS_ARGS" -e "INPUT_DOWNLOAD_LANGUAGE" -e "INPUT_SKIP_UNTRANSLATED_STRINGS" -e "INPUT_SKIP_UNTRANSLATED_FILES" -e "INPUT_EXPORT_ONLY_APPROVED" -e "INPUT_PUSH_TRANSLATIONS" -e "INPUT_COMMIT_MESSAGE" -e "INPUT_PULL_REQUEST_TITLE" -e "INPUT_PULL_REQUEST_BODY" -e "INPUT_PULL_REQUEST_LABELS" -e "INPUT_PULL_REQUEST_BASE_BRANCH_NAME" -e "INPUT_DOWNLOAD_TRANSLATIONS_ARGS" -e "INPUT_SKIP_REF_CHECKOUT" -e "INPUT_ADD_CROWDIN_BRANCH" -e "INPUT_NEW_BRANCH_TITLE" -e "INPUT_NEW_BRANCH_EXPORT_PATTERN" -e "INPUT_NEW_BRANCH_PRIORITY" -e "INPUT_DELETE_CROWDIN_BRANCH" -e "INPUT_CROWDIN_BRANCH_NAME" -e "INPUT_IDENTITY" -e "INPUT_CONFIG" -e "INPUT_DRYRUN_ACTION" -e "INPUT_GITHUB_BASE_URL" -e "INPUT_GITHUB_API_BASE_URL" -e "INPUT_GITHUB_USER_NAME" -e "INPUT_GITHUB_USER_EMAIL" -e "INPUT_GPG_PRIVATE_KEY" -e "INPUT_GPG_PASSPHRASE" -e "INPUT_BASE_URL" -e "INPUT_BASE_PATH" -e "INPUT_SOURCE" -e "INPUT_TRANSLATION" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/presales-localization/presales-localization":"/github/workspace" 786a9b:dc594fca37a745e0a94a236b50f9d1cd
STARTING CROWDIN ACTION
UPLOAD SOURCES
❌ Fetching project info
❌ Failed to collect project info. Please contact our support team for help
❌ Error from server: <Code: <empty_code>, Message: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
"; line: 1, column: 2]>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by andrii-bodnar** [comment]
Hi @laurentleseigneur, we can't reproduce it

is this issue still relevant to you?

**Comment by laurentleseigneur** [comment]
Hi andrii, this happen from time to time. I updated to latest version and it seems to be fixed, thus i will close this issue.

thanks for your answer.
