### ISSUE TITLE
modify sync schedule for users with owner role

### ISSUE THREAD

**Issue by dufcrule** [crowdin/github-action#144]
**Is your feature request related to a problem? Please describe.**
I'd like to edit a GitHub integration, specifically I'd like to change the sync schedule for a project. However, even as a user with the "owner" role, the `EDIT` button is disabled for me and I can't modify the sync schedule. This is because another user set the integration, and only the user that set the integration is able to edit it.

![Screenshot 2022-10-21 at 14 58 55](https://user-images.githubusercontent.com/51410533/197201478-944411b2-f69f-42c0-a909-f7cf1e50549c.png)

**Describe the solution you'd like**
I think that changing the sync schedule for a project is not critical from a security point of view. While I understand that other actions, like deleting the integration, should be protected, it seems that it's not necessary for this particular action. Indeed, as an owner I can delete the integration, but yet I can't modify a sync schedule if I didn't set up the integration. This seems inconsistent.

Perhaps there could be a way of modifying the sync schedule without using the Edit button? Maybe another button beside the `SYNC NOW` button? (e.g.: `CHANGE SCHEDULE` or similar). Or perhaps even as an option in the kebab menu?

![Screenshot 2022-10-21 at 14 55 58](https://user-images.githubusercontent.com/51410533/197200909-2158b0e3-07e7-4c97-9390-d2be5b20441c.png)

**Describe alternatives you've considered**
Alternatively, it could be allowed for owners (or even admins?) to edit certain elements of GitHub integrations, even if they're not the user that set the integration in the first place.

**Comment by andrii-bodnar** [comment]
Hi @dufcrule,

I'm closing this issue as it's not related to the Crowdin GitHub Action.

Please [contact]() our Customer Success Service or [Request a feature](https://crowdin.com/feature-request) for further consideration.

Thank you!

**Comment by dufcrule** [comment]
Sure, no worries! I'll submit this as a feature request instead. Thanks!
