### ISSUE TITLE
Take into account the export_languages parameter in configuration file

### ISSUE THREAD

**Issue by McGiverGim** [crowdin/github-action#152]
**Is your feature request related to a problem? Please describe.**
I'm not too sure if this is a feature request or a bug.
I'm using the action, and I want to download only some languages. The configuration file `crowdin.yml` has a parameter `export_languages` that can be used in VCS integrations to define the languages you want to export, or at least this is what I understand. I tried to use it but it's ignored. I have observed too that the Crowdin CLI ignores it too.

**Describe the solution you'd like**
I want to define in the `crowdin.yml` the `export_languages` parameter and the Action will only download this languages translations.

**Describe alternatives you've considered**
As a workaround, I'm using this in the Action:
> download_translations_args: '-l ca -l da -l de -l es-ES -l eu -l fr -l gl -l hr -l hu -l id -l it -l ja -l ko -l lv -l nl -l pt-PT -l pt-BR -l pl -l ru -l sv-SE -l zh-CN -l zh-TW'

but is less mantenible for collaborators than the `crowdin.yml` file.

**Additional context**
Nothing. Thanks for the Action!

**Comment by andrii-bodnar** [comment]
The `export_languages` option will conflict with the CLI `-l` arguments. It's recommended to use the command arguments in this case.
