### ISSUE TITLE
Docker Action - Exit Code 2

### ISSUE THREAD

**Issue by daegontaven** [crowdin/github-action#153]
**Describe the bug**
My crowdin action is exiting with code 2 because of docker.

```log
##[debug]Docker Action run completed with exit code 2
```

**To Reproduce**
1. [Crowdin Github Action Configuration](https://github.com/OpenDebates/openskill.py/actions/runs/3639383339/workflow)
2. [`crowdin.yml` file content](https://github.com/OpenDebates/openskill.py/blob/4bb863a66d838b91aa6bd3dc08b14a8a0b1a05e1/crowdin.yml)
3. OS: Ubuntu

**Expected behavior**
Docker exits with code 0

**Comment by daegontaven** [comment]
I've changed the `pull_request_reviewers` to an existing username. No change.

**Comment by andrii-bodnar** [comment]
@daegontaven ok, just for test purposes, could you please try removing the GPG configuration?

```
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
```

**Comment by daegontaven** [comment]
@andrii-bodnar Exit code changed, but build is still failing.

https://github.com/OpenDebates/openskill.py/actions/runs/3639997245/jobs/6144116690#step:7:839

**Comment by andrii-bodnar** [comment]
@daegontaven as I can see, now the execution reached the committing stage but there was nothing to commit. See the execution log:

```
Your branch is up to date with 'origin/main'.
```

**Comment by daegontaven** [comment]
But why is the build failing. Shouldn't it pass if there's nothing to commit?

**Comment by daegontaven** [comment]
As in it's a bug or as in it's supposed to error when there is nothing to commit?

**Comment by andrii-bodnar** [comment]
@daegontaven the last possible reason - try to remove the `pull_request_body` multiline value

sorry, we need your help with the debug 😬

**Comment by daegontaven** [comment]
@andrii-bodnar Same exit code.

https://github.com/OpenDebates/openskill.py/actions/runs/3640184556/jobs/6144553376#step:7:826

**Comment by andrii-bodnar** [comment]
@VBeytok could you please take a look? Maybe you will have some ideas

**Comment by andrii-bodnar** [comment]
Hi @daegontaven!

Found the cause of the failing action - it was related to `git-lfs`. Created a PR - #154 (It'll be released soon)

For now, you can revert the `pull_request_body` back, and also you can try the fix by referencing the exact repo branch:

```
uses: crowdin/github-action@Version-1.5.2
```
