### ISSUE TITLE
Missing Projects and Resources in `profile-menu dropdown-menu`

### ISSUE THREAD

**Issue by mbiesiad** [crowdin/github-action#155]
**Describe the bug**
Hi, not a big deal, but there are some quick fixes to do.
Please feel free to redirect this issue to other repo if needed.
(here I can see provided official site)

**To Reproduce**
1. Go to Profile as logged in user https://crowdin.com/profile/[name]/
2. Click on top left `profile-menu dropdown-menu` and compare with `navbar-inner application-navbar  nav-tabs__holder flex-grow-1`

**Expected behavior**
User has access to the mentioned missing elements.

**Screenshots**
Screenshot:
![image](https://user-images.githubusercontent.com/18367606/209463265-e32b2811-8557-4389-8185-e1004b0189b7.png)

Best wishes,
Michal

**Comment by DimaYashchyshyn** [comment]
Thanks for the report. We will investigate this.

**Comment by ira-sem** [comment]
Hi @mbiesiad !
The tab Profile home is the same as Projects. At the same time, resources = translation memories + glossaries
So in general, all the tabs can be accessed from the upper left menu
