### ISSUE TITLE
Can't use v1 as the major version

### ISSUE THREAD

**Issue by Goooler** [crowdin/github-action#159]
**Describe the bug**

See https://github.com/LawnchairLauncher/lawnchair/actions/runs/3941872319.
```
Unable to resolve action `crowdin/github-action@v1`, unable to find version `v1`
```

**To Reproduce**

1. Apply `uses: crowdin/github-action@v1` in GHA config.

**Expected behavior**

We can apply `v1` as the major version to always use the latest `1.x.y` like `actions/checkout@v1`.

**Comment by DimaYashchyshyn** [comment]
Hello, does it work with 1.5.3 being specified?

**Comment by Goooler** [comment]
Using `crowdin/github-action@1.5.3` is workable.

**Comment by andrii-bodnar** [comment]
@Goooler thanks for your request. Currently, we are not releasing the major v1 tag but I already thought about that and planned to automate such a release process in the nearest future.

**Comment by Goooler** [comment]
Seems you should tag your versions start with a `v`, see https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management.

**Comment by andrii-bodnar** [comment]
@Goooler yes, it's exactly what we a going to do, but we'd like to automate it with GH Actions. For example, like in this example - [update-main-version.yml](https://github.com/actions/checkout/blob/v3/.github/workflows/update-main-version.yml) or by using the [publish-action](https://github.com/actions/publish-action).

**Comment by andrii-bodnar** [comment]
BTW, we are happy to accept contributions! 🙂 

We'd like to prefer the `actions/checkout`'s approach with some changes.

**The desired workflow:**
- since we use Releases to create new versions, our new WF should be triggered on tag creation. So, when a new `v1.x.x` tag is pushed, the new workflow should run and force-push the `v1` tag.

Also, the `README.md` and `EXAMPLES.md` samples should be updated.

**Comment by andrii-bodnar** [comment]
@Goooler, I just released a new version of the Action and now it's possible to use the major `v1` version

https://github.com/crowdin/github-action/releases/tag/v1.6.0

**Comment by Goooler** [comment]
It works, thanks!
