### ISSUE TITLE
Ability to upload translations only for a certain language 

### ISSUE THREAD

**Issue by philippeauriach** [crowdin/github-action#16]
**Describe the solution you'd like**
I'd like to upload translations for only one language (french). I tried with `language` option but it seems it is only supported for downloading, not uploading.

**Describe alternatives you've considered**
Use the button "upload translations" in the github integration settings.

**Additional context**
When developing, developers write both in english (source) and french (one of our translated languages)

**Comment by VBeytok** [comment]
Hi @philippeauriach thank you for your suggestion!

We [added](https://github.com/crowdin/github-action/commit/861b545f8b535961c06a380ab77ef87ab3931c8d) option `upload_language`
Now you can set to one of your translated languages and upload translations only for a certain language.
