### ISSUE TITLE
Incorrect pull request query params

### ISSUE THREAD

**Issue by CzBiX** [crowdin/github-action#164]
**Describe the bug**
https://github.dev/crowdin/github-action/blob/bcc23e98ecf8b2605a9265fdc63c60228ad814e5/entrypoint.sh#L98

the `head` param in here will not works, the API will just return all PRs.
it should something like `org_name:branch_name`.
see docs: [here](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests)

**To Reproduce**
call GitHub API with `head` as simple branch name without `org_name`.

**Comment by andrii-bodnar** [comment]
@CzBiX We have not been able to reproduce the issue in the context of the current action. Could you please share a full WF Step configuration and steps to reproduce it?

**Comment by CzBiX** [comment]
example API request:
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/760097/234232729-7247c0c9-4b55-4579-b3e1-a0a088caf1e6.png">

The current code seems to work because the API ignores the head parameter and returns the last 30 PRs, which happen to have the PR corresponding to localization_branch_name.

It doesn't work when there are more than 30 PRs after localization branch a in the project.

**Comment by andrii-bodnar** [comment]
@CzBiX thanks for clarifying!

**Comment by rhys-saunders** [comment]
We've also been experiencing this issue recently. Is there a known fix for this?

**Comment by aysensolko** [comment]
Hello! @andrii-bodnar can you please answer when it will fixed?

**Comment by andrii-bodnar** [comment]
I'm thinking about switching to GH CLI instead of raw API calls - https://github.com/crowdin/github-action/issues/220
