### ISSUE TITLE
ARM runner support

### ISSUE THREAD

**Issue by xMikux** [crowdin/github-action#167]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/26039249/222092173-0326bb98-bd91-4e7f-95ea-ffada0730d53.png)
Current crowdin/cli only support amd64

**Describe the solution you'd like**
crowdin/cli can support multiarch, like amd64 and arm64, so runner can run it.

**Describe alternatives you've considered**
Actually, I rebuild the image to arm64 crowdin cli docker version, and make action to support, but will be great if official image can support it!

**Additional context**

**Comment by andrii-bodnar** [comment]
Duplicate - #160

@xMikux thanks for the suggestion!
