### ISSUE TITLE
Ability to download select languages

### ISSUE THREAD

**Issue by MajesticPotatoe** [crowdin/github-action#17]
**Is your feature request related to a problem? Please describe.**
From what I can tell at the moment you have one of 2 options: download all languages, or download a single language. This Feature would allow someone to specify a list of languages to download (akin to export_languages configuration property for VCS)

**Describe the solution you'd like**
Config property for downloading select languages something like
```
export_languages:
  - eo
  - en
  - ko
```

**Describe alternatives you've considered**
Right now I've done a multi-step approach (same step, just changing the single language) However i can only get this to work if using a separate branch for each language as actions throws an error `fatal: A branch named '<insertBranchNameHere>' already exists.` (which may merit a bug report)

**Additional context**
Open to other thoughts and ideas

Edit: to get around the branch checkout error, seems that you need to use `push_translations: false` on all steps except the last one. Not the greatest workaround but is doable.

**Comment by andrii-bodnar** [comment]
In the CLI [v3.9.0](https://github.com/crowdin/crowdin-cli/releases/tag/3.9.0) we've added the possibility to build multiple languages simultaneously:

```console
crowdin pull -l uk -l fr -l de
```

I would suggest renaming the existing parameter `download_language` -> `download_languages`, but **keep the backward compatibility** for older configs.

The new parameter `download_languages` should be able to receive language codes separated by a comma:

```yml
download_languages: 'uk,fr,de'
```

or single language as before:

```yml
download_languages: 'uk'
```

**Comment by andrii-bodnar** [comment]
Can be achieved via `download_translations_args`
