### ISSUE TITLE
Existing workflow - Failed to collect project info. Please contact our support team for help

### ISSUE THREAD

**Issue by sbulen** [crowdin/github-action#174]
**Describe the bug**
We have been using this github-action for over two years.

Our crowdin github actions started failing ~4 months ago with the following info.  Didn't notice this until today:  
![image](https://user-images.githubusercontent.com/23568484/236708612-987ecd06-07ad-45a4-8668-84e41118336f.png)

We tried using a more recent version of the github-action, and are now getting different "No source found" errors:
![image](https://user-images.githubusercontent.com/23568484/236708723-a87d055b-a953-45de-b801-09cc302b59a4.png)

**To Reproduce**
1. Crowdin GitHub Action configuration 
https://github.com/SimpleMachines/SMF/blob/release-2.1/.github/workflows/crowdin_wf.yml

2. `crowdin.yml` file content
https://github.com/SimpleMachines/SMF/blob/release-2.1/.github/crowdin.yml

**Expected behavior**
We expected source strings to be copied to CrowdIn, as in the past, and any new strings to become available for translation.  (We do not use the features where translations come back to github.)

**Comment by andrii-bodnar** [comment]
Hi @sbulen,

Please make sure you're using the latest version of the Action. The easiest way to do it - is to specify the major version only `crowdin/github-action@v1`.

**Comment by andrii-bodnar** [comment]
The `crowdin.yml` location causes the error. It's located inside the `.github` directory and as a result, CLI tries to find source files relative to this directory.

There are two ways to fix this:

- moving the `crowdin.yml` configuration to the root of the repo.
- updating the `base_path` option value: `../.`

**Comment by sbulen** [comment]
I am now getting this error.  Again, this workflow was working until 4 months ago:
![image](https://user-images.githubusercontent.com/23568484/236882907-15365b43-6c94-4430-8695-15cda4a8186d.png)

**Comment by sbulen** [comment]
Were the tokens changed?  Do we need to redo the token?

**Comment by sbulen** [comment]
Update:  We have two folders in CrowdIn for our project (SMF_2-1 & SMF_2-1_NEXT).  The 2nd folder is used for upcoming release info, for versioning.  Having it around allows translations for upcoming releases to proceed in parallel with updates to the current release.

The first folder works fine (SMF_2-1).   The 2nd folder (SMF_2-1_NEXT) gets the error above.  I can reproduce this behavior in my test environment as well.

So it's not a token/ownership issue, because the first one works OK now (same project ID, same secret token).  

But for some reason I cannot update the second folder.

**Comment by andrii-bodnar** [comment]
@sbulen could you please share your Crowdin project ID? It's better to share it by contacting our support team and mentioning this issue as a reference

**Comment by andrii-bodnar** [comment]
@sbulen thanks for the details. I checked from our side and it seems like your Crowdin personal access token doesn't have enough scope permissions for fetching all the needed information about the project.

Please try creating a token with the following scopes:

<img width="423" alt="Знімок екрана 2023-05-10 о 14 48 42" src="https://github.com/crowdin/github-action/assets/29282228/9719e26e-3b80-441d-b770-6e10374aeb85">

**Comment by sbulen** [comment]
Thank you for the quick response.  

I attempted the above in my test environment, and it did not work.  

As before, it works fine for the first folder (SMF_2-1), but not the second folder (SMF_2-1_NEXT).

I still get the "❌ You do not have permission to view/edit project with provided id." error.  As both are in the same project, I am using the same project ID and token for both.

I repeated the test with a new token that had **_ALL_** permissions, and the results were the same.  

The structure within CrowdIn looks like this:
![image](https://github.com/crowdin/github-action/assets/23568484/5a8ab8f2-4a13-49dd-9b6b-ed2c6a5c1e02)

**Comment by andrii-bodnar** [comment]
@sbulen it's very strange. Could you please try [Re-running the WF](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs) with the **debug logging** enabled?

**Comment by sbulen** [comment]
This is the main part...  If you want me to copy the whole thing let me know...

>  STARTING CROWDIN ACTION
> UPLOAD SOURCES
> ✔️  Fetching project info
> java.lang.RuntimeException: You do not have permission to view/edit project with provided id.
> 	at com.crowdin.cli.client.CrowdinClientCore$1.<init>(CrowdinClientCore.java:35)
> 	at com.crowdin.cli.client.CrowdinClientCore.<clinit>(CrowdinClientCore.java:28)
> 	at com.crowdin.cli.client.Clients.getProjectClient(Clients.java:45)
> 	at com.crowdin.cli.commands.picocli.ActCommandWithFiles.getClient(ActCommandWithFiles.java:30)
> 	at com.crowdin.cli.commands.picocli.ActCommandWithFiles.getClient(ActCommandWithFiles.java:11)
> 	at com.crowdin.cli.commands.picocli.GenericActCommand.run(GenericActCommand.java:37)
> 	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
> 	at picocli.CommandLine.access$1500(CommandLine.java:148)
> 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
> 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
> 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
> 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
> 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
> 	at picocli.CommandLine.execute(CommandLine.java:2170)
> 	at com.crowdin.cli.commands.picocli.PicocliRunner.execute(PicocliRunner.java:39)
> 	at com.crowdin.cli.Cli.main(Cli.java:16)
> ##[debug]Docker Action run completed with exit code 1
> ##[debug]Finishing: crowdin-action

**Comment by sbulen** [comment]
Note we are using a personal access token within the CrowdIn UI, and selecting all permissions.  I cannot specify branch/folder there.  This has been working for us for a while.

Is it possible the personal access token & the api token are now different (since January 2023) & cannot be interchanged anymore?  

Note I built a parallel test environment, and I am getting the same failure, even with a token with ALL permissions (pic below from test).  This new environment fails the same way, so the problem can be reproduced:
GH: https://github.com/sbulen/ci_gh_test1
CI: https://crowdin.com/project/crowdin-github-test

![image](https://github.com/crowdin/github-action/assets/23568484/0248d1d6-bd45-492d-8232-64e1609c1990)

This action has been running successfully in our production environment for ~2 years.  It was implemented in ~3/2021, and ran ok every week thru 1/14/23.  The 1/21/23 run was the first time it failed.  (Pic below from the production runs.)

![image](https://github.com/crowdin/github-action/assets/23568484/1b0c59dd-0575-480c-a064-4f4086d92c1d)

**Comment by andrii-bodnar** [comment]
@sbulen, please make sure that the account under which the token is created has manager permissions for the project

**Comment by sbulen** [comment]
Yes, confirmed the tokens were created by managers.

In my test environment,  I am also the site owner.

![Screenshot_20230517_064443_Firefox](https://github.com/crowdin/github-action/assets/23568484/ec0ed9af-a260-49bd-a5a5-9d4ae359fe98)

**Comment by andrii-bodnar** [comment]
@sbulen please try creating a token on the project owner's behalf for that environment where the action is failing

**Comment by sbulen** [comment]
No, that was production.

**Comment by sbulen** [comment]
I wonder if project-specific "granular" access is needed now...

**Comment by sbulen** [comment]
I just attempted creating a new token in test (as owner/manager) with granular access to the project in my test environment.

That failed similarly.

I sent a note to support with the project ID in test.  

I don't want to do too much experimentation in production.

**Comment by sbulen** [comment]
When I sent in the code for my test environment to support, they responded saying that my test run is failing because my free CrowdIn plan only supports one branch.

So... To be honest, I don't know if my production plan is failing for the same reason.  (I'm a volunteer! Not too familiar with the account details/history...)

I asked them if this is the reason for my production run failing as well.

**Comment by sbulen** [comment]
Closing the loop -  yes, recreating the token worked!

Thanks,

**Comment by DimaYashchyshyn** [comment]
Nice to hear that all works fine now :)
