### ISSUE TITLE
Use existing crowdin translations for new app

### ISSUE THREAD

**Issue by juliajulie95** [crowdin/github-action#179]
Hey there!

We have a crowdin project which is used for an android native app currently.
At the moment we are doing a rewrite in Flutter and would like to still use the translations from the old app.
They will both exist at the same time for a few years possibly.
Is there a way to fetch translation from crowdin that are already there and not use a source file in the current project?

**Comment by OlenkaCrowdin** [comment]
Hi @juliajulie95 !
We can recommend using bundles if you don't want to use source files:
https://support.crowdin.com/bundles/
