### ISSUE TITLE
make it easier to review translations in the pull request

### ISSUE THREAD

**Issue by moodysalem** [crowdin/github-action#183]
**Is your feature request related to a problem? Please describe.**
i would like to see just the new translations or translation changes in the pull request for downloaded translations, rather than all the context changes

**Describe the solution you'd like**
would be great if the default pr description offered a summary of the changes

**Describe alternatives you've considered**
n/a

**Additional context**
just context changes:
<img width="229" alt="image" src="https://github.com/crowdin/github-action/assets/7897876/0fec1a28-c60a-4ff7-919a-3adca84c70d0">

**Comment by andrii-bodnar** [comment]
@moodysalem could you please follow the "Feature Request" template for suggesting enhancements? Thank you.

**Comment by moodysalem** [comment]
> Also, please describe in more detail what you mean by "summary of changes".

<img width="923" alt="image" src="https://github.com/crowdin/github-action/assets/7897876/39aa7500-d98a-4664-83ba-02762cee8b44">
I moved some code around without changing any copy, extracted and uploaded the translations automatically via GH actions, then the download github action sent this PR with +/-2705 LOC for all the new context line numbers in the translation files

Really difficult for me to figure out based on this what's actually being downloaded

**Comment by andrii-bodnar** [comment]
The GH Action uses the [CLI](https://crowdin.github.io/crowdin-cli/) which uses the [Build Project Translation API](https://developer.crowdin.com/api/v2/#operation/api.projects.translations.builds.post) to download translation.

It returns just a ZIP archive with the translation files and there is no meta-information about the downloaded translations.
