### ISSUE TITLE
Crowdin CLI command fails if branch name contains a space

### ISSUE THREAD

**Issue by weakfl** [crowdin/github-action#192]
**Describe the bug**

Crowdin CLI command fails if branch name contains a space. eg. `pre-translate`:

```
STARTING CROWDIN ACTION
RUNNING COMMAND crowdin pre-translate -v --method tm --translate-with-perfect-match-only -i *** -T *** --branch "[project] branch-name"
Unmatched argument at index 11: 'branch-name"'
```

I tried with and without escaping the branch name.

**To Reproduce**

Try to execute `pre-translate` command with a branch name that contains spaces.

**Expected behavior**

Command shouldn't fail.

**Additional context**

refs https://github.com/crowdin/crowdin-cli/issues/620

@andrii-bodnar maybe it would make sense if standard env/parameters (`CROWDIN_PROJECT_ID`, `CROWDIN_PERSONAL_TOKEN`,  `crowdin_branch_name`) could be used and would be applied automatically as command arguments?

That being said, if the branch name would be escaped properly I'd be more than happy to use as is now.

**Comment by andrii-bodnar** [comment]
Hi @weakfl,

Could you please provide more details on how the command fails? I just tested how the CLI handles such branch names and it works as expected. So it is probably something on the Action side.

![image](https://github.com/crowdin/github-action/assets/29282228/7b03c508-9a4e-4c9b-a003-e6c850811f95)

**Comment by weakfl** [comment]
Hi @andrii-bodnar!

> I just tested how the CLI handles such branch names and it works as expected.

Confirmed, I tested it from the command line as well before creating this issue and it does work as expected.

> So it is probably something on the Action side.

Yes, definitely. Unfortunately there isn't much output from the workflow except the snippet I posted above:

```
Run crowdin/github-action@v1
  with:
    command: pre-translate
    command_args: -v --method tm --translate-with-perfect-match-only -i *** -T *** --branch "[project] branch-name"

[...]

STARTING CROWDIN ACTION
RUNNING COMMAND crowdin pre-translate -v --method tm --translate-with-perfect-match-only -i *** -T *** --branch "[project] branch-name"
Unmatched argument at index 11: 'branch-name"'
```

As you can see the brach name seems to be quoted so I'm not sure why it's failing.

**Comment by andrii-bodnar** [comment]
@weakfl thanks for the details!

I've made a possible [fix](https://github.com/crowdin/github-action/commit/1fd807be9ee29968ebbba2f31a1fc5183defd153), could you please check it by referencing the commit hash as the Action version?

```yml
uses: crowdin/github-action@1fd807be9ee29968ebbba2f31a1fc5183defd153
```

**Comment by weakfl** [comment]
@andrii-bodnar thanks, unfortunately the result is the same (tried with double and single quotes):

```
Run crowdin/github-action@1fd807be9ee29968ebbba2f31a1fc5183defd153
  with:
    command: pre-translate
    command_args: -v --method tm --translate-with-perfect-match-only -i *** -T *** --branch "[project] branch-name"

[...]

STARTING CROWDIN ACTION
RUNNING COMMAND crowdin pre-translate -v --method tm --translate-with-perfect-match-only -i *** -T *** --branch "[project] branch-name"
Unmatched argument at index 11: 'branch-name"'
```

```
Run crowdin/github-action@1fd807be9ee29968ebbba2f31a1fc5183defd153
  with:
    command: pre-translate
    command_args: -v --method tm --translate-with-perfect-match-only -i *** -T *** --branch '[project] branch-name'

[...]

STARTING CROWDIN ACTION
RUNNING COMMAND crowdin pre-translate -v --method tm --translate-with-perfect-match-only -i *** -T *** --branch '[project] branch-name'
Unmatched argument at index 11: 'branch-name''
```

**Comment by andrii-bodnar** [comment]
@weakfl could you please try the following?

```yml
command_args: -v --method tm --translate-with-perfect-match-only -i *** -T *** --branch [project]\ branch-name
```

Escaping the space by a backslash

**Comment by weakfl** [comment]
@andrii-bodnar unfortunately same result:

```
command_args: -v --method tm --translate-with-perfect-match-only -i *** -T *** --branch [project]\ branch-name

[...]

STARTING CROWDIN ACTION
RUNNING COMMAND crowdin pre-translate -v --method tm --translate-with-perfect-match-only -i *** -T *** --branch [project]\ branch-name
Unmatched argument at index 11: 'branch-name'
```

**Comment by andrii-bodnar** [comment]
@weakfl currently, as a workaround, you can use just CLI for this:

```yml
- name: Install Crowdin CLI
  run: npm i -g @crowdin/cli

- name: Run command
  run: crowdin pre-translate --method tm -i ${{ secrets.CROWDIN_PROJECT_ID }} -T ${{ secrets.CROWDIN_PERSONAL_TOKEN }} --branch "[project] branch-name"

```

**Comment by weakfl** [comment]
That works, thanks @andrii-bodnar

**Comment by andrii-bodnar** [comment]
> maybe it would make sense if standard env/parameters (CROWDIN_PROJECT_ID, CROWDIN_PERSONAL_TOKEN, crowdin_branch_name) could be used and would be applied automatically as command arguments?

This feature will be available in the next major release of the CLI (v4) and GitHub Action (v2). Already implemented - https://github.com/crowdin/crowdin-cli/pull/777
