### ISSUE TITLE
The action fails if a PR has already been created

### ISSUE THREAD

**Issue by Edivad99** [crowdin/github-action#195]
**Describe the bug**
The action fails if a PR has already been created

https://github.com/railcraft-reborn/railcraft/actions/runs/6210595744/job/16862732412
https://github.com/railcraft-reborn/railcraft/pull/118

**Comment by Edivad99** [comment]
I believe the problem is this commit: https://github.com/crowdin/github-action/pull/188/files

**Comment by andrii-bodnar** [comment]
Hi @Edivad99, I just released a [new version](https://github.com/crowdin/github-action/releases/tag/v1.13.1) of the Action. Could you please check if it works for you?

**Comment by Edivad99** [comment]
Now it works! Thanks
