### ISSUE TITLE
got docker: command not found

### ISSUE THREAD

**Issue by gasolin** [crowdin/github-action#196]
**Describe the bug**

the action was working for months, has issue from last week with error:

Build container for action use: '/home/user/actions-runner/_work/_actions/crowdin/github-action/v1/Dockerfile'.
  Error: docker: command not found

might related to yesterday's release https://github.com/crowdin/github-action/releases/tag/v1.13.0

**To Reproduce**
normal crowdin gh-action in github project
runs-on: ubuntu-latest

**Expected behavior**
work as usual

**Screenshots**

<img width="1016" alt="截圖 2023-09-19 下午4 47 29" src="https://github.com/crowdin/github-action/assets/748808/ec2c5a11-7f1b-415a-a3f0-91b9320dd194">

<img width="1049" alt="截圖 2023-09-19 下午4 51 33" src="https://github.com/crowdin/github-action/assets/748808/9a7cc54a-0544-42fe-ade5-776761d62517">

**Comment by andrii-bodnar** [comment]
@gasolin I can't reproduce it, everything works well on the `ubuntu-latest` and the `v1` version of the Crowdin Action.

Also please share your worklfow

**Comment by gasolin** [comment]
seems works fine again, will close the issue
