### ISSUE TITLE
Customizing pull request title and commit messages

### ISSUE THREAD

**Issue by zeke** [crowdin/github-action#20]
Hello again @VBeytok @andrii-bodnar, and @Bartlebyy 👋 

I just created a new workflow with this Action and it created a PR with the title `New Crowdin translations by Github Action`. This is clear enough (and it worked on the very first try with over 35,000 files 😍), but I'd like to be able to configure it so my project's commit messages and the pull request title are semantic, like `feat: new Crowdin translations`.

Is it possible to configure this in the Workflow? If not, consider this a feature request! :)

cc @alebourne

**Comment by andrii-bodnar** [comment]
Hello @zeke :wave:

We are happy to hear that you like this GitHub Action. Customizing pull request title and commit messages it's a great feature request! 

Thank you for the suggestion!
