### ISSUE TITLE
PR not created

### ISSUE THREAD

**Issue by BoboTiG** [crowdin/github-action#21]
**Describe the bug**

The PR is not created. In the action log, we can see:
```shell
# (...)
CONFIGURATION GIT USER
Switched to a new branch 'wip-translations-update'
PUSH TO BRANCH wip-translations-update
[wip-translations-update ba2445a] New Crowdin translations by Github Action
 1 file changed, 329 insertions(+)
 create mode 100644 nxdrive/data/i18n/i18n-eu.json
To https://github.com/nuxeo/nuxeo-drive.git
 + b009082...ba2445a wip-translations-update -> wip-translations-update (forced update)
CHECK IF ISSET SAME PULL REQUEST
CREATE PULL REQUEST
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "PullRequest",
      "field": "base",
      "code": "invalid"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request"
}
```
See [full logs](https://github.com/nuxeo/nuxeo-drive/runs/748147110?check_suite_focus=true).

The same action was working several day before: no code changes have been made either to the `crowdin.yml` file nor to the GitHub token.

**To Reproduce**

1. Crowdin Github Action configuration
2. [crowdin.yml file content](https://github.com/nuxeo/nuxeo-drive/blob/master/.github/workflows/crowdin.yml)

**Expected behavior**

The PR should be created.

**Comment by VBeytok** [comment]
Hi @BoboTiG !

Please update your workflow to [latest](https://github.com/marketplace/actions/crowdin-action) **crowdin-action** version. It should solve your issue.

**Comment by BoboTiG** [comment]
It is fixed, thanks a lot :)
