### ISSUE TITLE
skip_untranslated_strings from config is not respected

### ISSUE THREAD

**Issue by brawaru** [crowdin/github-action#212]
**Describe the bug**
Having `skip_untranslated_strings` set to `true` for some of the files in `crowdin.yml` is not respected by the action (CLI?) and results in translation files being downloaded pre-filled from source.

**To Reproduce**
1. Have `crowdin.yml` list some of the files which options have `skip_untranslated_strings` set to `true`.
2. Try downloading translating via the action.

**Expected behavior**
Untranslated strings are skipped in the downloaded files that have this option.

**Screenshots**
N/A

**Additional context**
Example from the repo I'm working on:
- Configuration file: https://github.com/brawaru/modrinth-knossos-2/blob/c9d5482b456266fcae78a0cdf04db3045b4638a4/crowdin.yml
- Download run: https://github.com/brawaru/modrinth-knossos-2/actions/runs/7790320762/job/21243925232
- Resulting export: [brawaru/modrinth-knossos-2@`d0ab4cf` (#2)](https://github.com/brawaru/modrinth-knossos-2/pull/2/commits/d0ab4cfe97d578bb67dc1e31b00291eb916b7473)

**Comment by andrii-bodnar** [comment]
@brawaru I just tested the `skip_untranslated_strings` set to `true` and it works as expected for me. 

The only thing that might be related to the JSON file format is the following - https://crowdin.github.io/crowdin-cli/faq#json-empty-string-keys (empty string keys on export)

**Comment by brawaru** [comment]
Odd. It kind of works by passing `--skip-untranslated-strings` to `download_translations_args` of the action, but this applies to all downloaded files, which is not future-proof (e.g., what if we'd need a file that should be always pre-filled with source? Or file that should not be downloaded if it's untranslated?):

- Workflow: https://github.com/brawaru/modrinth-knossos-2/blob/3c91eb1e08d24899e2c7f49390cd23e8832c4af2/.github/workflows/i18n-pull.yml#L26-L38
- Result: https://github.com/brawaru/modrinth-knossos-2/commit/3c91eb1e08d24899e2c7f49390cd23e8832c4af2

So I thought I'd individually change `skip_untranslated_strings` or `skip_untranslated_files` per file, but this is not working for whatever reason (see lines in the issue).

Is there some kind of way that these settings do not apply retroactively? That is, if file already exists on Crowdin and was uploaded without `skip_untranslated_strings`, then changing it later won't do anything.

Update 1: Just tried uploading sources again ([run](https://github.com/brawaru/modrinth-knossos-2/actions/runs/7800137144/job/21272351741), [crowdin.yml](https://github.com/brawaru/modrinth-knossos-2/blob/93090f25e5c6516fe36880aa4f9a161207bf6800/crowdin.yml)) and then downloading translations ([run](https://github.com/brawaru/modrinth-knossos-2/actions/runs/7800174526/job/21272455039)), but no, the downloaded files are still pre-filled with source strings ([commit](https://github.com/brawaru/modrinth-knossos-2/commit/c04d086fb2cae2ce5ec6b91549ae38e27da14149)).

Update 2: Deleted the files and re-uploaded them again ([run](https://github.com/brawaru/modrinth-knossos-2/actions/runs/7800261027/job/21272729648)), then downloading translations ([run](https://github.com/brawaru/modrinth-knossos-2/actions/runs/7800284712/job/21272795144)). The files still have the source strings in it ([commit](https://github.com/brawaru/modrinth-knossos-2/commit/fd2e79bc4e79959d3765fc84ed80bd3c0d5b091e)). So retroactive theory doesn't hold. I'm completely confused now, can you take a look and see if I'm doing anything wrong?

**Comment by andrii-bodnar** [comment]
@brawaru thanks for the details! Please try using the `skip_untranslated_strings` [Action input](https://github.com/crowdin/github-action?tab=readme-ov-file#download-options). As I can see from your `crowdin.yml` configuration file, you set the same `skip_untranslated_strings: true` for each file group, so there is no reason to do it at the config level.

To make sure the correct export option is passed in the API call, check the API logs of your Crowdin project. For example:

![Screenshot 2024-02-07 at 15 34 49](https://github.com/crowdin/github-action/assets/29282228/b0888731-42ba-4acf-a3b9-bc077b7945d5)

**Comment by brawaru** [comment]
I found the culprit! I believe it was because I had pre-processor enabled. Since I heard Crowdin will export empty strings and decided to see how I can delete those empty strings, but then quickly gave up. I didn't know how to remove the processor (you have to go to apps, find it there and uninstall), so I left it there thinking it wouldn't affect anything if it has no code, but apparently it did affect how translations are exported and caused all this confusion.

Sadly, though, it seems that I can only apply this option to all files at once and not individual files in `crowdin.yml` (which is quite confusing, why would it be [listed in documentation](https://developer.crowdin.com/configuration-file/#export-options) then). That is quite unfortunate in case we were to have files that cannot be partial (compared to all others that can skip untranslated strings)...

**Comment by andrii-bodnar** [comment]
@brawaru the mixed export options should work. I just remembered that some time ago I prepared a working example for this case. Please take a look - https://github.com/andrii-bodnar/crowdin-mixed-export-options-demo

**Comment by brawaru** [comment]
Oh, I think I see, it doesn't work if you specify `download_translations_args`, which I do to add `--all` argument (because we plan to have some source files automatically generated and it doesn't make sense to automatically generate them again just to download translations).

- [Export result without `download_translations_args`](https://github.com/brawaru/modrinth-knossos-2/commit/1dd20821f49d9e8af67a324e57be37290037e410) — almost what I'd expect, but skips `index.json` which is auto-generated
- [Export result with `download_translations_args`](https://github.com/brawaru/modrinth-knossos-2/commit/fad4ca594197ac2f3bf203d0092165c167cf83a7) — completely unexpected result (ignores the option)

**Comment by brawaru** [comment]
Oh, it's a problem with CLI, it downloads two different builds, but writes all files from each of them, thus overriding all files configured differently. I should've looked at the log, it's [pretty obvious](https://github.com/brawaru/modrinth-knossos-2/actions/runs/7822664759/job/21342170776#step:4:46).
