### ISSUE TITLE
Output more PR metadata.

### ISSUE THREAD

**Issue by joshhunt** [crowdin/github-action#215]
**Is your feature request related to a problem? Please describe.**

In our workflow, we continue to do additional automation on it, such as set correct milestones or add it to a project board. Usually these Github APIs require either the pull request _number_ (like `215`) or _id_ (like `PR_kwDOAOaWjc5mP_GU`), which is annoying to get from just the URL returned by this action.

**Describe the solution you'd like**

Output additional data from the created PR, such as number ([which it looks like the action already uses](https://github.com/crowdin/github-action/blob/38c22fcbd88b2a2d5939c1f02dfd64bb7508ae29/entrypoint.sh#L135C5-L135C25)) and ID. These should continue to default to being empty, like the URL, if the PR is not created.

**Describe alternatives you've considered**

We currently work around this by using an additional step to run a bash script with `gh pr view` to get the ID and number, but it would be much easier if the action just output this natively.

**Comment by andrii-bodnar** [comment]
@joshhunt already available in the latest Action version! [`v1.19.0`](https://github.com/crowdin/github-action/releases/tag/v1.19.0) (`v1` as well)
