### ISSUE TITLE
Workflow-Run (CI-Pipeline) not getting triggered for the Crowdin-PRs

### ISSUE THREAD

**Issue by tinogo** [crowdin/github-action#221]
**Describe the bug**
It seems to, that after creating (or updating) the Crowdin-PR using the Crowdin-Github-Action, no workflow-run of our CI-Pipeline gets started.
This is usually the case, if Git operations, as part of a job within a workflow, have been done with a repositories default token.

> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

Source: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow

**Expected behavior**
A workflow-run starts (if an alternative GITHUB_TOKEN has been provided)

**Screenshots**
![image](https://github.com/crowdin/github-action/assets/3515498/d5a13d5f-08ae-4fb5-8747-3ea56fe3f715)

Observe the "github-action" user, although we passed in a different Token for the crowdin-action (should have been the "Bike24-Bot").
As can also be seen, the PR itself gets created/maintained with the alternative token we pass to the crowdin-github-action, so this behaviour "just" needs to be extended to the Git operations as well. :)

**Comment by andrii-bodnar** [comment]
Hi @tinogo!

Could you please check the following approach?
https://github.com/crowdin/github-action/wiki/Run-tests-workflows-on-all-commits-of-a-PR

**Comment by tinogo** [comment]
Hi @andrii-bodnar,

thank you for your reply. This is actually, what I was searching for - I've completely overlooked this example.

Maybe it would be better to move this example (and the other ones) from the Wiki into the EXAMPLES.md (or the other way around)?

**Comment by andrii-bodnar** [comment]
@tinogo, glad to hear it works :)

Thanks for the suggestion, I will consider moving this to the examples.

**Comment by crhayes** [comment]
> Hi @tinogo!
> 
> Could you please check the following approach? https://github.com/crowdin/github-action/wiki/Run-tests-workflows-on-all-commits-of-a-PR

For anyone new arriving here, this documentation has now moved to https://github.com/crowdin/github-action/blob/master/EXAMPLES.md#run-test-workflows-on-all-commits-of-a-pr

**Comment by awoisoak** [comment]
In case it helps with someone else struggling with it. In my case I had to pass it to the `crowdin/github-action` itself for the nested CI to work.

```
- name: crowdin action
        uses: crowdin/github-action@v2.5.1
        with:
         ...
        env:
          GITHUB_TOKEN: ${{ secrets. GHA_CUSTOM_PAT }}
```

(When I tested it I was using and old github-action@v1 so that might potentially be the reason too)
