### ISSUE TITLE
Where is downloaded translations?

### ISSUE THREAD

**Issue by stdblue** [crowdin/github-action#235]
**Describe the bug**
I'm trying to create workflow for Nightly release.  
With crowdin/github-action I tried to download translations. It looks success.
But github actions script can't find translations file. 
Where is downloaded translations?

**To Reproduce**
1. Here is working repos : https://github.com/stdblue/scjpactions/actions/workflows/crowdin_sync.yml
2. `crowdin.yml` file is here : [crowdin.yml](https://github.com/stdblue/scjpactions/blob/main/.github/crowdin.yml)
3. [Tried job](https://github.com/stdblue/scjpactions/actions/runs/9640788130/job/26585185280)

**Expected behavior**
Access translation file global.ini and upload it as Release package.

**Screenshots**
Download has been succeeded.
![image](https://github.com/crowdin/github-action/assets/12421600/2cb6904a-7f62-444f-851f-7832942f0a1b)

But file can't access after process.
![image](https://github.com/crowdin/github-action/assets/12421600/a9c961f3-ab1f-4c70-a409-47752b886361)

**Additional context**
Crowdin target project : https://crowdin.com/project/star-citizen-ja

Thank you.

**Comment by andrii-bodnar** [comment]
Hi @stdblue, as I can see from the workflow run, the Crowdin Action has successfully downloaded the `release/Japanese/global.ini` file:

```console
DOWNLOAD TRANSLATIONS
✔️  Fetching project info
✔️  Building ZIP archive with the latest translations for 'ja'
✔️  Building translation (100%)
✔️  Downloading translations
✔️  Extracting archive
✔️  release/Japanese/global.ini
```

So I think the problem is in the `merge_global_from_crowdin.py` script, which I'm not familiar with as it contains logic unknown to me.

I would suggest looking into debugging this script. You can also try to add some debug steps to check the file structure after the translations download. Like this:

```
steps:
  # ... crowdin action

  - run: ls -la

  # merge script
```

Hopefully, this will help debug this issue.

**Comment by andrii-bodnar** [comment]
Thanks for the details!

Yes, actually it's expected. I think you can move the `crowdin.yml` to the repository root or try adjusting the `base_path` property in the following way:

```yml
"base_path": "../."
```

That's just an assumption, I haven't tested it myself. The best would be to move the `crowdin.yml` to the root + remove the `config` parameter from the Action setup.

**Comment by stdblue** [comment]
OK. Thank you.
Now my workflow has succeeded to create nightly build.
I will adjust my configurations.

I appreciate for your help.
Sincerely,
