### ISSUE TITLE
xcstring support for iOS projects

### ISSUE THREAD

**Issue by DevonJerothe** [crowdin/github-action#243]
**Is your feature request related to a problem? Please describe.**
Apple's xcstring format is a multilingual file. However, I am having trouble getting this to work via this action or the CLI as it requires source and translation entries to be separate using local codes. In this case the source file is also were the translations are stored. 

This is supported on Crowdins UI and I can build and download the singular xcstring file containing all languages. Is there something I am missing here or am I right to assume this is not supported via the GHA.

**Comment by andrii-bodnar** [comment]
Please check thins configuration - https://crowdin.github.io/crowdin-cli/advanced#multilingual-files
