### ISSUE TITLE
Xcode String Catalog is populated with all types of languages

### ISSUE THREAD

**Issue by caldrian** [crowdin/github-action#245]
**The bug**
We have started to upload Xcode String Catalogs using this crowdin/github-action:
```
 files: [{
  "source" : "/path/to/Localizable.xcstrings",
  "dest" : "/some/other/path/Localizable.xcstrings",
  "translation" : "%original_path%/%original_file_name%",
  "multilingual": true,
 }]
```
In the workflow we put:
```
upload_sources: true
download_translations: true
upload_translations: false
create_pull_request: true
```
The downloaded string catalog then contains far too many localisation keys:
```
["ar", "be", "bg", "bn", "ca", "cs", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fr", "he", "hr", "hu", "id", "is", "it", "ja", "ka", "ko", "lt", "lv", "ms", "my", "nl", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "si", "sk", "sl", "sr-CS", "sr-SP", "sv", "th", "tr", "uk", "ur-PK", "vi", "zh-Hans", "zh-Hant"]
```
The localisation key "sr-SP" even triggers a warning from AppStore connect:
```
ITMS-90176: Unrecognized Locale
```

**Expected behavior**
The downloaded string catalog should have the same languages as the .strings and .stringsdict files.

**Comment by andrii-bodnar** [comment]
@caldrian: This is related to the process of exporting the xcstrings file format, not the action itself. 

Please [contact](https://crowdin.com/contacts) our Customer Success team for further investigation. Sorry for the inconvenience!
