### ISSUE TITLE
Issue downloading translations with different paths 

### ISSUE THREAD

**Issue by Surkhojb** [crowdin/github-action#246]
**Describe the bug**
Issue downloading translations in a directory path when the source is following a different path, project was created before using github action to download translations.
**To Reproduce**
1. Crowdin GitHub Action configuration
```     - name: Crowdin Translations
        uses: crowdin/github-action@v2.1.2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          export_only_approved: false
          create_pull_request: false
          push_sources: false
          push_translations: false

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_ACTION_TOKEN }}
```
3. `crowdin.yml` file content
```
#
# Your Crowdin credentials
#
"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env":  "CROWDIN_PERSONAL_TOKEN"
"base_path": "Android"
"base_url": "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": false

#
# Files configuration
#
files: [
  {
    #
    # Source files filter
    # e.g. "/resources/en/*.json"
    #
    "source": "Android/strings.xml",

    #
    # Where translations will be placed
    # e.g. "/resources/%two_letters_code%/%original_file_name%"
    #
    "translation": "app/src/main/res/values-%two_letters_code%/strings.xml",
  }
]

```
5. Error from the action
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/c7812814-346f-40de-b8ca-b6960485998d">

**Expected behavior**
The expected behaviour should be able to support a different path for the source and different path for the download.

**Screenshots**
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/7816a048-fe3b-45a3-a8fa-dc8919e61e31">

**Additional context**

**Comment by andrii-bodnar** [comment]
Hi @Surkhojb!

Have you tried the recommendations listed on the [FAQ](https://crowdin.github.io/crowdin-cli/faq#due-to-missing-respective-sources-the-following-translations-will-be-omitted) page?

**Comment by Surkhojb** [comment]
Hi @andrii-bodnar 

I tried different cli commands but I got same result as the action. I am not able to download my translations if are not following the same folder structure as android studio project.

**Comment by andrii-bodnar** [comment]
@Surkhojb in this case you can try using the `download_translations_args` configuration with the `--all` value.

[`download translations` command reference](https://crowdin.github.io/crowdin-cli/commands/crowdin-download-translations).

**Comment by Surkhojb** [comment]
@andrii-bodnar I tried as you mentioned and this is the output I am getting from `crowding cli`
![image](https://github.com/user-attachments/assets/09670f66-5a33-42b3-883f-89aa52ea4aec)

**Comment by andrii-bodnar** [comment]
@Surkhojb it's definitely the **Resulting file after translations export** issue described in the CLI FAQ.

The translations the CLI receives have the following structure: `<code>/strings.xml/strings.xml`. I guess it's not expected.

Try to upload your source file via CLI to the project. It will set the right export pattern for the `strings.xml` file.

**Comment by Surkhojb** [comment]
@andrii-bodnar The problem is if I try to push the sources, my project structure is not `Android/strings.xml` my project structure is based on Android Studio path `app/src/main/res/values/strings.xml`.

So basically I want to be able to download whatever I have previously `Android/strings.xml` and put it here `app/src/main/res/values/strings.xml`.

So is a way to do this without pushing again the sources just to follow the project's path?

Thanks.

**Comment by andrii-bodnar** [comment]
@Surkhojb to keep the source file structure in Crowdin the same as you currently have, try the `dest` parameter. ([reference](https://developer.crowdin.com/configuration-file/#uploading-files-to-specified-path-with-specified-type)).

In this case, you probably won't need to set `preserve_hierarchy: false` in your config file.

Something like this:

```yml
"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env":  "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

files: [
  {
    "source": "/app/src/main/res/values/strings.xml",
    "dest": "/Android/strings.xml",
    "translation": "/app/src/main/res/values-%two_letters_code%/strings.xml",
  }
]
```

Please note that I changed the `base_path` and `source` values.

**Comment by Surkhojb** [comment]
Hi @andrii-bodnar I made some progress after your suggestion:

- `crowdin.yml`
```
#
# Your Crowdin credentials
#
"api_token": "af117f50d776e2bbfb97fb89632c5a5a519d298c2272dc8db770d895beca1dd820405cd69857292d"
"project_id": "713867"
"base_url": "https://api.crowdin.com"
base_path: "."

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
  {
    "source": "/app/src/main/res/values/strings.xml",
    "dest": "/Android/strings.xml",
    "translation": "/app/src/main/res/values-%two_letters_code%/strings.xml"
  }
]
```

So I tested the following command and I can hit and download the sources `crowdin download sources`
<img width="910" alt="image" src="https://github.com/user-attachments/assets/7a46f19f-0901-4218-896f-907e13a5830e">

But once I try to run the following command is when now I am not able to download the translations `crowdin download sources`

<img width="905" alt="image" src="https://github.com/user-attachments/assets/dee62f6e-fb76-40b9-a9cb-a8d71ec3b3c6">

Those are the languages in the dashboard:
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/e91360a5-3bad-4a7b-9b40-14072537e012">

**Comment by andrii-bodnar** [comment]
@Surkhojb you need to run the `crowdin upload` command first to set the correct Translations Export pattern based on the configuration file.

Please also avoid posting API tokens here. Please revoke it as soon as possible.

**Comment by Surkhojb** [comment]
Awesome @andrii-bodnar now it works!. Don't worry about the token. I will revoke it. Thanks for the support!

**Comment by andrii-bodnar** [comment]
@Surkhojb great, thanks for confirming!
