### ISSUE TITLE
Pull request actions are broken

### ISSUE THREAD

**Issue by mikey0000** [crowdin/github-action#254]
**Describe the bug**

When running a crowdin action (based on defaults)

it errors with 
error: pathspec 'translations-and-connections' did not match any file(s) known to git

The project is checking out `/usr/bin/git checkout --progress --force refs/remotes/pull/194/merge`

Project is open source you can check it all out here 
https://github.com/mikey0000/Mammotion-HA/actions/runs/11563272177/job/32186224855
https://github.com/mikey0000/Mammotion-HA/pull/194

**To Reproduce**
1. Crowdin GitHub Action configuration
2. `crowdin.yml` file content
3. Information about workflow (OS, steps, etc.)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mikey0000** [comment]
I've resorted to using it on commit which works fine for my use case.

**Comment by mintplo** [comment]
@mikey0000
Hello,
how to solve this problem?
this happen to me same.

**Comment by andrii-bodnar** [comment]
Hi @mikey0000, please provide more details about your issue.
