### ISSUE TITLE
Describe default configuration in README

### ISSUE THREAD

**Issue by lifehackerhansol** [crowdin/github-action#255]
**Is your feature request related to a problem? Please describe.**

Currently I have no idea which option in the actions is "default". During testing I enabled `download_translations: true` and I got sidetracked from the actions uploading sources for some reason, and also requiring GITHUB_TOKEN environment variable for... something.

With no idea what the default configurations are I have no idea which one I need to override to have the action do exactly what I would like it to.

**Describe the solution you'd like**

Document the default configuration of the actions workflow in README or wiki.

**Describe alternatives you've considered**

No alternatives I have considered at this time.

**Additional context**

You can find my workflow below. (Renamed from `.yml` due to limitation of GitHub upload.)

[crowdin-commit.txt](https://github.com/user-attachments/files/17839287/crowdin-commit.txt)

**Comment by lifehackerhansol** [comment]
I just found out `EXAMPLES.md` exists; while this does help the particular workflow uploaded above, I'd still like to know what the defaults are for future reference.

**Comment by bmuenzenmeyer** [comment]
agree - defaults are necessary, this made for some costly mistakes I had to clean up this week
