### ISSUE TITLE
Subsequent pushes to existing PR/branch lead to stuck PR actions

### ISSUE THREAD

**Issue by Yserz** [crowdin/github-action#34]
**Describe the bug**
When a fresh PR/branch is created by the action it seems to use the provided `GITHUB_TOKEN` so the owner of the token is displayed as creator of the PR. When an update to this PR is pushed from the action it seems it uses the default `github.token` and `github-actions` is the creator of the push. This seems to not allow to run other actions on the updated PR (I suspect to prevent infinite loops). Here's an example: https://github.com/wireapp/wire-webapp/pull/9696.

**To Reproduce**
1. Change the translations files in order to create a new PR/branch with the action (creator will be `otto-the-bot` and other actions are running through)
2. Add another change and trigger the action (push is created by `github-actions`)
3. Other actions running on this PR are stuck and never complete.

**Expected behavior**
Subsequent pushes are created from `otto-the-bot` instead of `github-actions`

**Comment by Yserz** [comment]
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token

**Comment by ottosuess** [comment]
we're also having this problem.
in our case it's really annoying because we're running the action to create the PR with a cron job.
every time the job runs and there is already a PR all the checks get invalidated and don't run again. (because the action also force pushes when translation have not changed.)

**Comment by andrii-bodnar** [comment]
https://github.com/crowdin/github-action/wiki/Handling-parallel-runs

**Comment by ottosuess** [comment]
how is this issue related to parallel runs?

has this been fixed?

**Comment by andrii-bodnar** [comment]
@ottosuess do you have some ideas on how this issue might be fixed? Are there any alternative solutions or features you've considered?

**Comment by zomars** [comment]
We're having the same issue. We used auto update with kodiak. When that happens, checks start running again. But minutes later the crowdin action force pushes and the checks gets cancelled.

**Comment by zomars** [comment]
Even setting a `workflow_run` as trigger doesn't trigger the checks as [described in the docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run).

**Comment by DimaYashchyshyn** [comment]
Thanks @zomars we'll check this.

**Comment by zomars** [comment]
Here's an example https://github.com/calcom/cal.com/pull/6444

**Comment by wojsmol** [comment]
Hi all
Please see this comment by me on https://github.com/crowdin/github-action/issues/142#issuecomment-1773770133
