### ISSUE TITLE
Does the upload_sources command also *update* source files?

### ISSUE THREAD

**Issue by courtneycb** [crowdin/github-action#39]
I would like to achieve 4 things using GitHub Actions:

1. Update source message files
2. Push source files to Crowdin
3. Build project on Crowdin
4. Pull translations from Crowdin

I see I can achieve 2. and 4. using the `upload _sources` and `download_translations`options. But I was wondering if `upload_sources` also updates source files if they have changes?

Is there also a way to trigger building the project translations using this action? Or will I have to create my own action for that?

Sorry I wasn't sure where else to ask these questions! Thanks heaps.

**Comment by andrii-bodnar** [comment]
Hi @courtneycb!

Sure, the `upload_sources` command updates source files in Crowdin if they have changed.

> Is there also a way to trigger building the project translations

The build is automatically triggered in the `download_translations` command.

**Comment by courtneycb** [comment]
Thanks so much @andrii-bodnar!! 😄
