### ISSUE TITLE
Add support for placeholders similar to crowdin.yml GitHub Integration

### ISSUE THREAD

**Issue by Andre601** [crowdin/github-action#45]
**Is your feature request related to a problem? Please describe.**
I would like to switch to this Action to no longer requiring a dedicated Account for up and downloading the files, but from a Conversation with a Support-Member did I find out, that this action doesn't seem to support placeholders like `%locale%` or `%fileextension%` within `commit_message` or `translation`?

Quote from the Mail:
> I'm afraid currently it doesn't work in this way. But you're welcome to add this to the issue and our developers will fix it :
https://github.com/crowdin/github-action/issues

**Describe the solution you'd like**
Add support for changing the placeholders similar to the CLI or GitHub Integration.

**Describe alternatives you've considered**
There aren't really any other alternatives I could think of other than staying with the current system of having a dedicated account.

**Additional context**

**Comment by andrii-bodnar** [comment]
Hi @Andre601!

Have you consider options `commit_message`, `pull_request_title` or `pull_request_body`?

You can find all the available options in the [Supported Options](https://github.com/crowdin/github-action#supported-options) section of the Readme.

**Comment by Andre601** [comment]
This is not what I was mentioning in my issue.

As I just said there did I had a conversation with the Crowdin support where it was pointed out that placeholders don't seem to be supported (yet) within the GitHub Action.

I in fact even mentioned that "[...] this action doesn't seem to support placeholders like `%locale%` or `%fileextension%` within `commit_message` or `translation`?"

While `commit_message` wouldn't be a big problem is `translation` a required option to support the placeholders, so that translations would be saved within the right directory and as the right file format (`%locale%.%fileextension%` would become de_CH.json)

**Comment by Olena1234** [comment]
Hello @Andre601 

Placeholders are specified in the configuration files, kindly check an article on the matter below:
https://support.crowdin.com/configuration-file/#writing-a-simple-configuration-file

The following placeholders are supported in Crowdin:
https://support.crowdin.com/configuration-file/#placeholders

**Comment by Andre601** [comment]
So how would the configuration look like when migrating from an existing github integration?

**Comment by Olena1234** [comment]
Configuration file would look just the same as for the integration. Here you may check more details about the migration:
https://github.com/crowdin/github-action/issues/7

**Comment by Andre601** [comment]
> Configuration file would look just the same as for the integration. Here you may check more details about the migration:
> #7

Doesn't really help me that much tbh.
I have this PR open right now to implement the GitHub Action in the hope to "retire" the dedicated User account for translations.
What exactly would I need to update to make everything work like the old system?

**Comment by Andre601** [comment]
To add to this does #7 not help me at all since the linked project on GitHub is no longer available and therefore can't be looked at to understand the file-structure.
As much as I appreciate the help would I appreciate it more if it was an actual, up-to-date viewable example and not one that has been deleted since.

**Comment by Olena1234** [comment]
Hi! Sorry for the delays, I'm passing your comments to our devs and will come back with updates on the matter

**Comment by Andre601** [comment]
I quickly updated [my comment](https://github.com/crowdin/github-action/issues/45#issuecomment-797481544) with a bit more info (mainly added and updated some links)

**Comment by Olena1234** [comment]
Got it, thanks!

**Comment by VBeytok** [comment]
Hi @Andre601 
Please check this [pull request ](https://github.com/purrbot-site/PurrBot/pull/312)
`commit_message` is supported only in workflow without placeholders (not in the config file of github actions or cli)
In case commit is needed for each language separately, then steps should be created for each language. Just like [here](https://github.com/purrbot-site/PurrBot/pull/312/files#diff-719333b616448c4150fe3848e76b55fbb9864ef46fe9543509fef22ca2cef2acR46).

**Comment by Andre601** [comment]
> Hi @Andre601
> Please check this [pull request ](https://github.com/purrbot-site/PurrBot/pull/312)
> `commit_message` is supported only in workflow without placeholders (not in the config file of github actions or cli)
> In case commit is needed for each language separately, then steps should be created for each language. Just like [here](https://github.com/purrbot-site/PurrBot/pull/312/files#diff-719333b616448c4150fe3848e76b55fbb9864ef46fe9543509fef22ca2cef2acR46).

That's kind of the point for this issue then.
Not having such placeholders available is frustrating, especially if you switch from the setup using an Account.

**Comment by DimaYashchyshyn** [comment]
Hi @Andre601 
Thanks for the prompt reply, passing your comments to the team

**Comment by DimaYashchyshyn** [comment]
Currently, Crowdin Github Action works on Crowdin CLI and it can build all languages or just one

**Comment by Andre601** [comment]
Any updates or similar on this one?
While I honestly don't care about the action anymore (Just seemed to useless for my case to warrant a switch) would I still like to know if there has been any progress about this within the past year.

**Comment by TaniaMal** [comment]
Hi @Andre601!

I will double-check this with the team and come back to you

**Comment by andrii-bodnar** [comment]
Hi @Andre601!

The Crowdin GitHub Action already supports all the placeholder configurations that are available in the CLI or GitHub integration. Actually, GH Action is based on Crowdin CLI.

Could you please check the [usage](https://github.com/crowdin/github-action#usage) and [supported options](https://github.com/crowdin/github-action#supported-options) sections?
