### ISSUE TITLE
Do not PR when no string or translations changed

### ISSUE THREAD

**Issue by eMerzh** [crowdin/github-action#52]
**Is your feature request related to a problem? Please describe.**
I have setup the auto PR with this actions, however, now it create a new PR with only metadat of my PO changing
(namely the  "PO-Revision-Date: 2021-02-11 00:42\n" changing )

**Describe the solution you'd like**
only PR if there's actually string change (source or translations)

**Describe alternatives you've considered**
letting this as is.... but it does make some noise that if i could avoid, would be cool

**Additional context**
- PR for po file format

**Comment by Olena1234** [comment]
Hello @eMerzh 

The only thing that we can suggest here is to set up [schedule](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events) or [workflow_dispatch](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch) for launching the workflow. Hope this helps!

**Comment by eMerzh** [comment]
@Olena1234 thanks for the help ... unfurtunatly  i'm not sure it helps... 
i DO use schedule... but the thing create/update a PR even when there's no string changes (source or translated)

see below:
![image](https://user-images.githubusercontent.com/177003/110760902-7876a200-824f-11eb-8f6c-6397108949e5.png)

if i could filter that out, and create the PR only when actual strings are changing, that would really help :)

**Comment by Olena1234** [comment]
Could you please consider using one of the following features?
 skip_untranslated_strings  
 skip_untranslated_files  
 export_only_approved


They could be selected in the project settings -> General tab
https://support.crowdin.com/advanced-project-setup/#export

**Comment by Olena1234** [comment]
Just one more thing, those options can be specified in your workflow directly as well:
https://github.com/crowdin/github-action#supported-options

**Comment by alexandernanberg** [comment]
@Olena1234 Can you elaborate a little more on how to get `workflow_dispatch` work with Crowdin? Not sure if I'm missing something but adding a webhook doesn't offer you to specify custom headers for auth etc which Github requires

<img width="852" alt="image" src="https://user-images.githubusercontent.com/8997319/111321651-6f7b3b80-8668-11eb-9a3c-762cb2e904a7.png">

**Comment by BohdanSitarskyi** [comment]
@alexandernanberg Just double-checked everything for you, and as for now there is no possibility to specify the custom header for Crowdin.

It is possible though for our Crowdin Enterprise platform.

**Comment by eMerzh** [comment]
@Olena1234 sorry to come back this long after, 
but this is still bothering me :p 

skip_untranslated_strings, skip_untranslated_files, export_only_approved 
do not helps... they still download the file if the date has changed for some reason....

but might be an issue within crowdin-cli in fact 🤔

**Comment by TaniaMal** [comment]
Hi @eMerzh!

Sorry for the inconveniences!

Could you please send us the link to your project in Crowdin so we could check everything?

**Comment by andrii-bodnar** [comment]
Closed due to inactivity

**Comment by FelixMalfait** [comment]
Same issue for us, we end up with long useless PRs like this one: https://github.com/twentyhq/twenty/pull/10157/files

Related issues:
- https://github.com/crowdin/crowdin-cli/issues/81
- https://github.com/crowdin/crowdin-cli/issues/183

@andrii-bodnar should I open a new issue? I couldn't find a solution from the previous issues. Thanks a lot!

**Comment by andrii-bodnar** [comment]
Hi @FelixMalfait!

We can't do anything at the CLI/Action level with this, since it already receives the updated file and has no information about the actual string updates, it just works at the file level. From Crowdin's perspective, it always updates the `Po-Revision-Date` header on export.

Currently, I see two ways to deal with this:

- Use the [Custom Post-Export Processor](https://store.crowdin.com/custom-post-export-processor) application to replace or remove the `Po-Revision-Date` header. It shouldn't affect anything, but the date would be incorrect or inaccurate in this case.
- Configure the GH Action workflow trigger to use the [Webhooks-based approach](https://store.crowdin.com/github-actions-webhook). In this case, the action will only download new translations when new translations are added. However, it requires more complex setup to download only updated languages and not all at once.

**Comment by FelixMalfait** [comment]
Great @andrii-bodnar I think the Post-Export should work for us! Thanks a lot


Two things if anyone comes to this thread:
- The Post-Export processor has moved to the Settings > File Processor sections, it isn't in the Tools section as in the app's screenshot
- The textarea is too small for the modale so you need to edit the CSS height to reveal a submit button below

<img width="488" alt="Image" src="https://github.com/user-attachments/assets/0d504acd-b64e-44a1-bb8c-d4d9506811a7" />
