### ISSUE TITLE
Need more flexibility with placeholders

### ISSUE THREAD

**Issue by sbulen** [crowdin/github-action#55]
**Describe the bug**
Our translated files are in the same folder, e.g., 
> /yada/yada/languages/admin.english.php
> /yada/yada/languages/admin.dutch.php

Specifying the following in crowdin.yml gets us very close:
>   "source" : "/yada/yada/languages/*.english.php",
>   "translation" : "/yada/yada/languages/%file_name%.%language%.php",

But our output ends up looking like:
> /yada/yada/languages/admin.english.dutch.php

We need to be able to be able to strip the '.english' part out of the translated file name.

I couldn't find a way to do this - is it feasible?

See also #45

**Comment by andrii-bodnar** [comment]
Hi @sbulen!

In this case, you could use the `translation_replace` option - [docs](https://support.crowdin.com/configuration-file/#renaming-translations-file)

This will allow you to strip '.english' from translation files.

**Comment by sbulen** [comment]
WOW thank you for the quick response.  I will experiment with that!  

THANX!

**Comment by sbulen** [comment]
I think we can close this...
