### ISSUE TITLE
crowdin.yml security

### ISSUE THREAD

**Issue by sbulen** [crowdin/github-action#56]
**Describe the bug**
Testing this action, I got repeated errors that my api_token and project_id were missing from crowdin.yml.  So I added them, & everything worked.  But...  The api_token and project_id are exposed when you do that.  I tried using GitHub secrets to hide them, but crowdin wasn't very happy with that...

See also #55 and #45 

**Expected behavior**
I expected to be able to hide the api_token and project_id when the crowdin.yml file is up on github.  OR...  Operate a github action without having a crowdin.yml at all.  

**Additional context**
If there is a way to do an action with NO crowdin.yml, that would be great.  But then we need to be able to use placeholders within the github action, and become dependent on #45 .

**Comment by andrii-bodnar** [comment]
Hi @sbulen!

To keep your credentials secret you need to use [Environment variables](https://support.crowdin.com/configuration-file/#api-credentials-from-environment-variables).

**Comment by sbulen** [comment]
I completely misunderstood that section of the docs.  

Thank you for the prompt response!  I'll close this out....
