### ISSUE TITLE
GitHub action adds "/" to translation

### ISSUE THREAD

**Issue by sbulen** [crowdin/github-action#58]
**Describe the bug**
If you have a simple translation with a placeholder in crowdin.yml, e.g.:
`  translation: "Admin.%language%.php",`

What ends up in the Translations export field in CrowdIn is:
`/Admin.%language%.php`

The problem is that added "/" at the beginning of the string disrupts the normal build/download function in CrowdIn.  Without the "/", you get each language in its own folder, and the file hierarchy is preserved - as expected.  With that added "/", however, all languages are in one folder, and it is flat.  It is overriding the preserve_hierarchy setting somehow.

Current crowdin.yml I'm using for testing is:
https://github.com/sbulen/crowdin_test/blob/1d0e8cb1784fd90c2d630c0683070c4f93d39100/crowdin.yml#L22

**Expected behavior**
I want the translation spec to be exactly what I pass - no added "/".  That way, the normal build/download will work as expected.

**Screenshots**
When the translation field looks like this:
![image](https://user-images.githubusercontent.com/23568484/108605885-bd539b00-736b-11eb-8004-f3125aa711ba.png)

The build/download looks as expected:
![image](https://user-images.githubusercontent.com/23568484/108605961-1cb1ab00-736c-11eb-9cfb-900dd5f7defa.png)

But when the GitHub action has added the "/" to the translation field:
![image](https://user-images.githubusercontent.com/23568484/108605869-ab71f800-736b-11eb-824f-db8a80417f74.png)

The build/download gets flattened out, and no longer honors one folder per language:
![image](https://user-images.githubusercontent.com/23568484/108605918-e07e4a80-736b-11eb-8015-1579753a224d.png)

**Additional context**
We have an uneven hierarchy - translated files are two different locations.

**Comment by denisqua** [comment]
@sbulen hi there!

Thanks a lot for reporting this!

Let us re-check with developers that behavior and get back to you with an answer :)

**Comment by denisqua** [comment]
Hi @sbulen again!

Coming back with updates regarding opened issue:

Could you please change a bit your configuration file (crowdin.yml)? 

Translation path should be changed to: `translation: "%locale%/Admin.%language%.php"`

So then you'll get files by languages as expected (via build and via Crowdin/GitHub action as well)

Thanks,

**Comment by sbulen** [comment]
Thank you - I tried a couple variations on that & found one that worked.  Since I had a non-flat structure, it looked a little more like:
![image](https://user-images.githubusercontent.com/23568484/109105971-bd44f980-76e3-11eb-89da-847055baf250.png)

And the builds look perfect now:
![SecondTry-1](https://user-images.githubusercontent.com/23568484/109106013-d483e700-76e3-11eb-99e9-9963a7d2f96a.png)
