### ISSUE TITLE
CGHA features not supported on CrowdIn site

### ISSUE THREAD

**Issue by sbulen** [crowdin/github-action#59]
**Is your feature request related to a problem? Please describe.**
I would like the crowdin.yml specs to be completely honored throughout CrowdIn - including when you use the CrowdIn site to perform builds & downloads.  There are at least 2 features that are not honored, or, cause issues when performing builds/downloads on CrowdIn.com:
 - wildcards
 - translation_replace

When you use wildcards, multiple issues occur.  First, since we have 'english' in the source file names, it gets included on the download.  E.g., "Admin.english.php" as a source becomes "Admin.english.dutch.php" post translation.  The second issue is that the translation spec, if it has any path information in it at all, flattens out the directory structure & puts all languages in one big folder (see also #58 for screenshots).   

When you use translation_replace to fix the english.dutch to dutch problem, that works fine throughout CGHA & CLI, but not when you do builds & downloads on the CrowdIn site.  

**Describe the solution you'd like**
I would like to use wildcards in my CGHA, and have that honored when I do builds & downloads on CrowdIn.

**Describe alternatives you've considered**
It feels like once you've gone in on CLI/CGHA, you're all in, and using build/download on CrowdIn won't work...  You need to do file manipulation via the API to get it all to tie together.

Today, I can get around these problems by (1) hardcoding my list of filenames to avoid the english.dutch issue, and (2) I manually tweak the 'translation' field to remove "/"s after source import via CGHA.  

**Additional context**
See Issue #55 , #58 , #45 

I have an uneven site hierarchy with two locations (all languages are in one folder, but the site agreement is in the root folder).  

Our naming convention always has the language in the filename, e.g., we ultimatlely want:
   `Admin.english.php`
to be translated to 
   `Admin.dutch.php`

THANX!!!  This is a very well thought-out product, all in all.

**Comment by andrii-bodnar** [comment]
The `translation_replace` option specified in the configuration file can't affect the UI/API build. 

It can be done by modifying the `translation` pattern. After pushing sources via CLI or CGHA the "Resulting file after translations export" will be updated and it will affect UI/API downloads as well.
