### ISSUE TITLE
Download translations without pushing to branch

### ISSUE THREAD

**Issue by pedrofracassi** [crowdin/github-action#6]
Could you guys make it so we are able to download translations without pushing to a branch on the repository? I want to download our translated strings and package them into our Docker Images without having to push translations to the repo.

Thanks a bunch :)

**Comment by VBeytok** [comment]
Hi @pedrofracassi !

We [added](https://github.com/crowdin/github-action/commit/20cebe1f52b1776b2be1c79451d3d5905b6d1ed0) option `push_translations` now you can set it to `false` and download translations without pushing to branch.

**Comment by pedrofracassi** [comment]
Thank you so much!
