### ISSUE TITLE
CGHA on forks...

### ISSUE THREAD

**Issue by sbulen** [crowdin/github-action#62]
**Describe the bug**
Is there an approach or best practice to somehow disable the workflows on all forks of a repo?

The CrowdIn GitHub Action works great!  Almost too great...

So I have an action working fine that periodically pushes source from GitHub to CrowdIn.

I also have literally hundreds of forks...  Folks use the forks, of course, to submit PRs to our project.  The CGHA is (or will soon be) running on those, too...  

It fails, since they don't have the SECRETs configured with credentials as on the main site...  But it feels wasteful (& a little dangerous) to have them all executing at all.

GitHub isn't too helpful with this question, as their articles just say to disable the WFs on the forks...  How, exactly, do I do that?  There should be a better way...  Maybe a way to trigger an early, safe,  abort if the SECRETs aren't there?

**Comment by VBeytok** [comment]
Hi @sbulen, you can add to your workflow check like this `if: env.CROWDIN_PERSONAL_TOKEN != null` after `-name` of step,  and if not exist secret it will be skipped.

**Comment by sbulen** [comment]
That sounds very promising - will give it a try!

**Comment by sbulen** [comment]
Yes, this works great, thank you!

I would suggest putting that on any examples...

**Comment by DimaYashchyshyn** [comment]
Hi, 

Glad to hear it worked 🙂 We'll take your comments into account

**Comment by sbulen** [comment]
I am reopening this...

With the "if:" condition there, the forks properly bypass the steps, however, the main job now fails...  It says there is no crowdin.yml.  It is no longer honoring the .config setting in the workflow...

![image](https://user-images.githubusercontent.com/23568484/111943126-fcbbf700-8a91-11eb-9925-271cbd5187ee.png)

The crowdin.yml file is identified by a .config setting:
![image](https://user-images.githubusercontent.com/23568484/111943622-fed28580-8a92-11eb-82bf-bb312af379a8.png)

The secrets are defined.  Yes, the workflows include the token in the env: section:
![image](https://user-images.githubusercontent.com/23568484/111943245-4a386400-8a92-11eb-92ed-2aae8a6d7f16.png)

The crowdin.yml file includes the env variables:
![image](https://user-images.githubusercontent.com/23568484/111943358-7d7af300-8a92-11eb-80c9-373beed1620c.png)

This worked until the "if:" was introduced.  I do not understand how the "if:" introduced this issue.

Thanks for all the help,

**Comment by ira-sem** [comment]
Hi!
Passing the info to our developers!

**Comment by ira-sem** [comment]
Hi @sbulen! could you please try the following pull request?
https://github.com/sbulen/crowdin_test/pull/10

Let us know how it goes!

**Comment by sbulen** [comment]
Thank you for the response!

It failed with the same issue:
https://github.com/sbulen/crowdin_test/actions/runs/676717558

**Comment by VBeytok** [comment]
Hi @sbulen, this [merge request ](https://github.com/sbulen/crowdin_test/pull/10) was for workflow `crowdin_wf.yml`, [here](https://github.com/sbulen/crowdin_test/pull/11) is for `crowdin_wf_next.yml`

**Comment by sbulen** [comment]
🤦‍♂️

Yes.  It helps to use the right file.  Thank you, this works!
