### ISSUE TITLE
Skip certain languages

### ISSUE THREAD

**Issue by M123-dev** [crowdin/github-action#65]
**Is your feature request related to a problem? Please describe.**

The flutter localisation package we use does not provide some languages, at the time only 78 are supported. The problem is with every crowdin run, even the unsupported languages are committed, which leads to a error.

**Describe the solution you'd like**
The possibility to skip some languages.

**Describe alternatives you've considered**
That you can specify which ones should be commited.

**Comment by andrii-bodnar** [comment]
This should work - https://github.com/crowdin/github-action/wiki/Separate-PRs-for-each-language
