### ISSUE TITLE
Download translation option does not work with pull-request based events

### ISSUE THREAD

**Issue by dzonatan** [crowdin/github-action#66]
Download translation option (with `push_translations`) does not take into account that `GITHUB_REF` not always refer to a branch name. For pull-requests the `GITHUB_HEAD_REF` should be used instead.

Therefore this line breaks:
https://github.com/crowdin/github-action/blob/331321924bd16fd3b1cf1d693c6bc35047e70ba0/entrypoint.sh#L116

With:
```
error: pathspec 'refs/pull/14/merge' did not match any file(s) known to git
```

**Comment by ira-sem** [comment]
Hi @dzonatan! Already passed it to our developers and will keep you posted!

**Comment by dominikager** [comment]
any progress?

**Comment by ira-sem** [comment]
Hi @dominikager! Our developers are still working on the case, sorry for the delay!
we will keep you updated!

**Comment by nosteine** [comment]
I also have this issue.
@dzonatan - Do I understand correctly that for pull-requests, this line will work ?
` git checkout "${GITHUB_HEAD_REF#refs/heads/}" `

**Comment by bitttttten** [comment]
Also running into this :) Is there a way to patch the action? Before the fix gets released?
