### ISSUE TITLE
Crowdin Action does not create PR and fails with error:     jq: error (at <stdin>:4): Cannot index string with string "head"

### ISSUE THREAD

**Issue by sumitahluwalia** [crowdin/github-action#67]
**Describe the bug**
Pull request does not get created when the crowdin executed is executed.
The script fails with error:
```
 jq: error (at <stdin>:4): Cannot index string with string "head"
```

**To Reproduce**
1. I previously had github integration enabled for the same project. I just tried to switch to using the action.
2. I have the action added here: https://github.com/sumitahluwalia/crowdin/blob/main/.github/workflows/main.yml
3. You can see my action executed here: https://github.com/sumitahluwalia/crowdin/runs/2417311249
4.  crowdin.yml file: https://github.com/sumitahluwalia/crowdin/blob/main/crowdin.yml

**Expected behavior**
The PR request should be created.

**Additional context**
```
STARTING CROWDIN ACTION
UPLOAD SOURCES
✔️  Fetching project info
✔️  File 'FileToTranslate.json'
UPLOAD TRANSLATIONS
✔️  Fetching project info
✔️  Translation file 'Translations/fr.json' has been uploaded
✔️  Translation file 'Translations/en.json' has been uploaded
DOWNLOAD TRANSLATIONS
✔️  Fetching project info
✔️  Building ZIP archive with the latest translations
✔️  Building translation (100%)
✔️  Downloading translation
✔️  Extracted: 'Translations/en.json'
✔️  Extracted: 'Translations/fr.json'
CONFIGURATION GIT USER
Already on 'main'
M	Translations/en.json
M	Translations/fr.json
Your branch is up to date with 'origin/main'.
Switched to a new branch 'l10n_crowdin_action'
PUSH TO BRANCH l10n_crowdin_action
[l10n_crowdin_action d62d3e9] New Crowdin translations by Github Action
 2 files changed, 12 insertions(+), 20 deletions(-)
To https://github.com/sumitahluwalia/crowdin.git
 + 6355e60...d62d3e9 l10n_crowdin_action -> l10n_crowdin_action (forced update)
CHECK IF ISSET SAME PULL REQUEST
jq: error (at <stdin>:4): Cannot index string with string "head"
```

**Comment by og-fox** [comment]
Hi @sumitahluwalia! I'm sorry to hear you were faced with such behavior and thank you a million for bringing this to our attention! Already asking the tech team to take a look

**Comment by sumitahluwalia** [comment]
> Hi @sumitahluwalia! I'm sorry to hear you were faced with such behavior and thank you a million for bringing this to our attention! Already asking the tech team to take a look

Thanks a lot for the quick response! Please let me know incase I can use any work around as well for this.

**Comment by VBeytok** [comment]
@sumitahluwalia Hi sorry for so fast response 🥲 , is the problem exists?

**Comment by VBeytok** [comment]
Hi @subbuswaroop! Let's try first set new version of github action `uses: crowdin/github-action@1.4.0` and re-run action.

**Comment by subbuswaroop** [comment]
@VBeytok Were you able to find anything? 🙂

**Comment by subbuswaroop** [comment]
@VBeytok Thank you for the response. But I'm still getting the same error even after using the default `${{ secrets.GITHUB_TOKEN }}`. I can see that a new branch is getting created. But only the PULL_REQUEST fails. Do I need to delete the branch and try running the script again? Will that work?

**Comment by subbuswaroop** [comment]
@VBeytok Sorry for the dumb response earlier. I was actually changing the `${{ secrets.GITHUB_TOKEN }}` in another workflow file and was expecting the current one to work 😒. 

It's working now. Thank you very much. Have a great day :)

**Comment by googol7** [comment]
I just had the same problem and was able to solve it by using:

`GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

Does the documentation need an update? [Here](https://github.com/marketplace/actions/crowdin-action) for example you write:

`GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}`

In this official video https://youtu.be/5b7BMuCoKGg?t=382 he says:

"You do need to have a secrets.GITHUB_TOKEN. You can create your GitHub by yourself. You can also use an automatic one that GitHub provides."

That doesn't seem to be true.

**Comment by andrii-bodnar** [comment]
@googol7 please refer to the [Permissions](https://github.com/crowdin/github-action?tab=readme-ov-file#permissions) section in the Readme.

> In case you want to use an [automatic GitHub authentication token](https://docs.github.com/en/actions/security-guides/automatic-token-authentication), you need to assign the [write permission to your job](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) and [allow GH Actions to create Pull Requests](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#preventing-github-actions-from-creating-or-approving-pull-requests).

**Comment by googol7** [comment]
Could the error message be improved when there's a problem with the token?
