### ISSUE TITLE
Name of the agency registered when adding an existing review 

### ISSUE THREAD

**Issue by CamilleMery98** [crowdin/github-action#68]
**Describe the bug**![bug name on reviews](https://user-images.githubusercontent.com/77099391/116858762-3179ad00-abff-11eb-888c-788894b43918.png)A clear and concise description of what the bug is.
When an agency adds a comment from one of its clients and validates it on their behalf, their name are registered instead of the name of their client. 

**To Reproduce**
1. Crowdin Github Action configuration
2. `crowdin.yml` file content
3. Information about workflow (OS, steps, etc.)
On an agency profile : you go to "reviews" and "add an existing review". Then you add the existing review, complete the clients' personal info and you validate. 

**Expected behavior**
The review appears when the client validates it through the confirmation email. And the review is supposed to be at his name. 

**Screenshots**
In the screenshot, we see the name of one of the founders of the agency (Paradelo) instead of the name of their client.

![bug name on reviews](https://user-images.githubusercontent.com/77099391/116858762-3179ad00-abff-11eb-888c-788894b43918.png)**Additional context**

**Comment by Natalia936** [comment]
Hi Camille, could you please kindly clarify how the investigated bug is connected with GitHub action and maybe there is a chance to share more details with us?

Thank you in advance 😉
