### ISSUE TITLE
Configuration file is invalid

### ISSUE THREAD

**Issue by zeke** [crowdin/github-action#7]
Hey @andrii-bodnar, @VBeytok, and @Bartlebyy! 👋 

Thanks for creating this action! I'm really excited to start using it on our localization projects at GitHub. We've been using the OAuth app integration for some time, but using this Action could give us much more flexibility around how and when we sync our GitHub repo with our Crowdin project. 😎 

I created a [sample public repo](https://github.com/docs/crowdin-action-test) and corresponding [sample public Crowdin project](https://crowdin.com/project/crowdin-action-test) to try it out, but ran into an error:

```
❌ Configuration file is invalid. Check the following parameters in your configuration file:
	- Required option 'project_id' is missing in the configuration file
	- Required option 'api_token' is missing in the configuration file
```

Is this referring to my `crowdin.yml` configuration file? I would think not, as that would require me to add secrets to the file and save them in source control.

I have also set the (numeric) project ID and a personal access token in the repo secrets:

![Screen Shot 2020-05-02 at 7 18 46 PM](https://user-images.githubusercontent.com/2289/80897047-c4f56680-8ca9-11ea-8638-7bd53cdcd3d4.png)

---

- Public repo: https://github.com/docs/crowdin-action-test
- Public Crowdin project: https://crowdin.com/project/crowdin-action-test
- Failing check: https://github.com/docs/crowdin-action-test/runs/639771316?check_suite_focus=true

Thanks for any help on this. I'd be happy to contribute to this project and help improve the documentation once I get my setup working.

cc @andrulko @alebourne @juliangruber

**Comment by og-fox** [comment]
Hi @zeke !
Please, add these credentials to your config file `crowdin.yml`:
```
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
```

**Comment by og-fox** [comment]
Also, thanks a lot for supporting us! We'd be happy to hear your ideas and feedback on action :)

**Comment by zeke** [comment]
Hi @og-fox. Thanks for the quick reply?

Do you mean I should paste exactly that code into my `crowdin.yml` and it will somehow be substituted with the secret values from the ENV at runtime?

**Comment by VBeytok** [comment]
Hi @zeke !

**Comment by zeke** [comment]
That worked! I added this to my `crowdin.yml`:

```
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
```

And I got farther along! But now I'm seeing this:

```
Switched to a new branch 'l10n_crowdin_action'
DOWNLOAD TRANSLATIONS
✔️  Fetching project info
❌ Branch with the specified name doesn't exist in the project. Try specifying another branch name
```

I'm not sure which branch it's referring to. I have `crowdin_branch_name: translations` set in my [workflow file](https://github.com/docs/crowdin-action-test/blob/1a0d0682f0298b8aaaeedf22ee619a42b50abf27/.github/workflows/crowdin.yml#L22). Is that referring to a git branch or a Crowdin branch? I remember that Crowdin has a concept of "branches" that differ from git branches. Do I need to create that branch in the git repo first?



https://github.com/docs/crowdin-action-test/runs/640027661?check_suite_focus=true

**Comment by og-fox** [comment]
@zeke, that parameter is referring to a branch in Crowdin project and it seems there is currently no branches in your project. Could you please try adding one? I believe it's work flawlessly once there is a branch in a project :)

**Comment by zeke** [comment]
Ok I created a branch called `translations` in Crowdin:

<img width="1043" alt="Screen Shot 2020-05-02 at 11 53 46 PM" src="https://user-images.githubusercontent.com/2289/80907952-30eac580-8cd0-11ea-9c59-6513ea4bcfa1.png">

And I pushed up an empty commit to trigger the workflow again. Now everything is green 🍏 but the output is `NOTHING TO COMMIT`: https://github.com/docs/crowdin-action-test/runs/640046225

Perhaps I have misconfigured something. What does `crowdin_branch_name` refer to? Is it the name that Crowdin will use for the git branch it creates for the pull request? Or is it the name of the "branch" in the Crowdin project? 

My goal is to end up with a new pull request that adds the localized files to my project.

**Comment by zeke** [comment]
Also to clarify: My end goal is to have Crowdin only consume my `master` git branch (not any other feature branches), and I would like Crowdin to create a PR using a git branch named `translations` (though that doesn't matter as much as long as it works).

**Comment by og-fox** [comment]
@zeke, thanks for clarification of workflow! Already checking with the team on your questions and will get back with summary as soon as I have answers

**Comment by VBeytok** [comment]
Hi @zeke !

Please remove [dryrun_action](https://github.com/docs/crowdin-action-test/blob/master/.github/workflows/crowdin.yml#L23) option in your workflow.
It use for `Print a command output without execution`

**Comment by zeke** [comment]
Thanks for the PR https://github.com/docs/crowdin-action-test/runs/640811167?check_suite_focus=true !

I merged it and made some more progress. Now I'm seeing this:

```
UPLOAD TRANSLATIONS
✔️  Fetching project info
⏭  'translations/zh-CN/content/some-article.md' translation file doesn't exist in the specified place
⏭  'translations/fr-FR/content/some-article.md' translation file doesn't exist in the specified place
⏭  'translations/es-ES/content/some-article.md' translation file doesn't exist in the specified place
⏭  'translations/zh-CN/content/nested/some-nested-article.md' translation file doesn't exist in the specified place
⏭  'translations/fr-FR/content/nested/some-nested-article.md' translation file doesn't exist in the specified place
⏭  'translations/es-ES/content/nested/some-nested-article.md' translation file doesn't exist in the specified place
⏭  'translations/zh-CN/data/some-datafile.yml' translation file doesn't exist in the specified place
⏭  'translations/fr-FR/data/some-datafile.yml' translation file doesn't exist in the specified place
⏭  'translations/es-ES/data/some-datafile.yml' translation file doesn't exist in the specified place
⏭  'translations/zh-CN/data/nested/some-nested-datafile.yml' translation file doesn't exist in the specified place
⏭  'translations/fr-FR/data/nested/some-nested-datafile.yml' translation file doesn't exist in the specified place
⏭  'translations/es-ES/data/nested/some-nested-datafile.yml' translation file doesn't exist in the specified place
CONFIGURATION GIT USER
Switched to a new branch 'l10n_crowdin_action'
DOWNLOAD TRANSLATIONS
✔️  Fetching project info
✔️  Building ZIP archive with the latest translations
✔️  Building translation (100%)
✔️  Downloading translation
Downloaded translations don't match the current project configuration. The translations for the following sources will be omitted (use --verbose to get the list of the omitted translations):
- nested/some-nested-article.md (3)
- nested/some-nested-datafile.yml (3)
- some-article.md (3)
- some-datafile.yml (3)
NOTHING TO COMMIT
```

Here's the check run: https://github.com/docs/crowdin-action-test/runs/640852471

The file structure I've created here in this repo is a basic copy of my real Crowdin project, with a `content` directory full of markdown files and a `data` directory full of YAML files:

```
~/git/docs/crowdin-action-test master
$ tree 
.
├── LICENSE
├── README.md
├── content
│   ├── nested
│   │   └── some-nested-article.md
│   └── some-article.md
├── crowdin.yml
└── data
    ├── nested
    │   └── some-nested-datafile.yml
    └── some-datafile.yml
```

This is what I see on my real Crowdin project:

<img width="525" alt="Screen Shot 2020-05-03 at 10 32 54 AM" src="https://user-images.githubusercontent.com/2289/80921173-8ef7c700-8d29-11ea-902d-c9b31becb571.png">

But on the new test project, the `data` and `content` directories are not being preserved on the Crowdin side:

<img width="597" alt="Screen Shot 2020-05-03 at 10 33 24 AM" src="https://user-images.githubusercontent.com/2289/80921180-a3d45a80-8d29-11ea-902c-d8bb03dba6f3.png">

I used the existing `config.yml` file from my real project (with a few slight modifications) so I think the config is correct, and would expect the directory structure on Crowdin to match my repo:

```yml
files:
  - source: /content/**/*.md
    translation: /translations/%locale%/%original_path%/%original_file_name%
  - source: /data/**/*.yml
    translation: /translations/%locale%/%original_path%/%original_file_name%
```

Thanks again for all the help!

**Comment by VBeytok** [comment]
@zeke to save structure you need to use this [option](https://support.crowdin.com/configuration-file-v3/#saving-directory-structure-on-server) in your config file
```
preserve_hierarchy: true
```

**Comment by zeke** [comment]
Thanks @VBeytok. It worked! 🎉

Here's the first pull request: https://github.com/docs/crowdin-action-test/pull/2 ✨ 🍕 ✨ 

Very awesome. 😎 

I opened PRs #8 and #9 to clarify documentation for some of the issues encountered along the way.

**Comment by VBeytok** [comment]
@zeke thanks, looks good! Need wait @andrii-bodnar to approve and merge pull requests

**Comment by zeke** [comment]
I'm going to close this, and may open followup issues if I encounter other problems.

Thanks again for the quick and helpful responses. 🏆 🍹

**Comment by Andre601** [comment]
Is there now a working example? I have serious problems to understand this GH Action and to get it working.

There is an open issue I created (Linked above, #45) where I ask for help, so if someone has a working example for me would I be thankful for it.
