### ISSUE TITLE
Add reviewer(s) when creating a pull-request

### ISSUE THREAD

**Issue by dzonatan** [crowdin/github-action#71]
Would be great if this action had built-in support for adding reviewers to the pull-request.
Example: `pull_request_reviewers: ['userA', 'userB']` optional option

**Comment by denisqua** [comment]
@dzonatan Hi there! Thanks for provided improve idea!

I'll pass directly to the tech guys 😉

**Comment by andrii-bodnar** [comment]
The solution could be similar to the `pull_request_assignees` option in https://github.com/crowdin/github-action/pull/138

**Comment by ultr4nerd** [comment]
Hey! Can I take this?

**Comment by andrii-bodnar** [comment]
Hi @ultr4nerd, sure, thank you!
